clabs <- cbk[, "clab"]
clabs <- c("African Americans",
           "Approach Evaluation",
           #"'At Risk' Populations",
           "Secondary/Archival Data",
           #"Asian Americans",
           "IPV Perpetrator Interventions",
           "Community Capacity",
           "Coordinated Community Response",
           #"Cis-Gender",
           "College Students",
           "IPV Consequences",
           "Couples",
           #"Non-IPV Crime Victims",
           #"Case Study",
           #"Disabled Persons",
           #"IPV Dynamics",
           "Experimental Design",
           "Females/Women/Girls",
           "Focus Groups",
           "General Population",
           #"Graduate Students",
           "HIV Intervention/Prevention",
           "Help-Seeking",
           "Intervention/Prevention (General)",
           "Intervention Description",
           "Intervention Proposal",
           "IPV-Perpetrators",
           "IPV-Victims/Survivors",
           "Interviews",
           "Latinos/Latinas or Hispanic-Americans",
           "Longitudinal",
           "Males/Men/Boys",
           "Measures",
           "Multi-Method QuaLitative Design",
           "Multi-Method QuaNTitative Design",
           "Mixed-Methods",
           "Research/Evaluation Methods",
           #"Perpetrator Characteristics",
           "Program/Policy Development",
           "Outsiders' Perspectives",
           "Practitioners' Perspectives",
           #"Key Stakeholders' Persepctives",
           "Victims'/Survivors' Perspectives",
           "Program/Policy Evaluation",
           #"Protective Factors",
           "Public Policy",
           "Non-IPV Community-Based Practitioners",
           "IPV-Specific Community-Based Practitioners",
           "IPV Prevention",
           "IPV Prevalence",
           "IPV Intervention Programs",
           "Parents",
           "QuaLitative",
           "QuaNTitative",
           "Client Records",
           "Police/Court Records",
           "Risk Factors",
           "IPV Screening",
           #"Racial Minorities",
           "Sexual Minorities",
           "QuaLitative Survey",
           "QuaNTitative Survey",
           "Non-IPV System Entities",
           "System Response",
           "Urban-Specific",
           "IPV Victimization Interventions",
           "Cross-Sectional",
           "Children/Youth")
