# I. Background & Significance

The purpose of the present review is to ultimately inform intervention and prevention strategies specific to same-gender intimate partner violence among sexual minority women (SMW). Over the past several decades, there has been a considerable development of research and community action across the globe working to address intimate partner violence (IPV). In the United States, this research and activism stemmed primarily from first-and-second-wave feminist movements, which collectively led way to the U.S. Violence Against Women and, more specifically, the U.S. Domestic Violence Movement beginning around the 1980s. The public policies and community-based services specific to intimate partner violence resulting from this mainstream work continue to be almost exclusively focused on men's abuse toward women [ e.g., @black2011national; @tjaden2000full]. Consequently, intimate partner violence occurring among members of the Lesbian, Gay, Bisexual, Transgender, and Queer (LGBTQ) population has been critically overlooked and the IPV-related needs of this population have gone unmet with severe consequences<!--**RS1.** NAME THESE CONSEQUENCES--> [@ristock2001decentering; @walters2013national]. Importantly, recent nation-level data indicate that LGBTQ individuals experience IPV at rates comparable to heterosexual individuals, and are in many ways at higher risk of experiencing violence than heterosexual population<!--**RS2.** NAME THESE WAYS OF INCREASED RISK--> [@walters2013national]. Pertinent to this study, these data provide evidence that the prevalence of female same-sex intimate partner violence (FSSIPV) in particular occurs at much higher rates than expected by researchers conducting national-scale intimate partner violence survey work [@walters2013national]. This, along with historic data corroborating these statistics,<!-- **RS3.** CITE--> suggests that the prevalence of FSSIPV has been grossly misrepresented throughout the U.S. Women's and Domestic Violence Movements. The causes and consequences of this misrepresentation lie in historical notions that regard female same-sex intimate partner violence as a phenomenon that is either non-existent [@cecere1986second], not possible [@hammond1989lesbian], or not worthy of consideration based on anti-LGBTQ ideological viewpoints [@durish2011documenting; @ristock2001decentering; @ristock2011intimate]. The relative lack of research on female same-sex IPV is characteristic of a long history of oppressions committed against sexual and gender minorities and traditional gender role stereotypic expectations of women to be nonviolent, or the notion that women do not possess the ability to be violent, or at least violent enough to inflict pain on others [@gilbert2002discourses; @girshick2002no; @hassouneh2008influence; @little2010perceptions].

In line with the heteronormative stereotypic notion of women's incapability of violence, FSSIPV-inclusive research to date has tended to fall into one or both of the following categories: (1) reports of the estimated national prevalence of FSSIPV; and/or (2) heterosexual groups' and individuals' gender role stereotypes about women's same-gender relationships, and the possibility of violence in those relationships<!-- **RS4.** REVISIT--> [e.g., @mcclennen2005domestic; @messinger2011invisible]. Compared to attention given to issues collectively faced by the LGBTQ population, the relatively large dedication of federal, state, and private funding for research related to violence against women and domestic violence since the original signing of the Violence Against Women Act (VAWA) has been almost exclusively used for developing services for presumed heterosexual, cis-gender, female survivors of abuse perpetrated by male intimate partners with similarly presumed heterosexual and cis-gender characteristics [@ristock2001decentering]. However, results of research related to IPV occurring within this narrowly defined population are not necessarily representative of the prevalence, causes, and correlates of IPV experienced by members of the LGBTQ population [@burke1999violence; @hassouneh2008influence; @ristock2001decentering]. Thus, domestic violence services that emerged out of the U.S. Women's and Domestic Violence movements of the 1980s and 1990s (e.g., emergency shelters for survivors and batterer intervention programs), which are largely based on this heterosexual-IPV-focused research, remain ill-equipped to serve LGBTQ IPV survivors, perpetrators, and their families [@hart1986lesbian; @lobel1986naming; @mclaughlin2001knowledge; @ristock2001decentering; @smith2011women].
<!-- In recent years, however, researchers have begun to address the lack of empirical knowledge around the prevalence and causes of intimate partner violence among Lesbian, Gay, Bisexual, Trans, and Queer populations by adding distinctions of sexual orientation to existing national intimate partner violence inquiries and reports [@walters2013national]. -->

## Rationale

The above-described barriers to IPV-related research, intervention, and prevention efforts specific to sexual minority women necessitate a research approach that takes into account this unique context. Community psychological theory values the notion that the communities in which research is taking place and/or affecting (whether directly or indirectly) should be as involved as possible in all phases of the research process, rather than solely as anonymous data points in the analysis. Community psychology thus favors inclusion over exclusion, participant voices equally with researchers' voices, and participatory and/or purposive sampling methods over convenience sampling methods. The reviewed literature will be evaluated and critiqued according to these types of community psychological standards regarding (1) _research methodologies_, (2) _data analytic approaches_, (3) _interpretations of findings_, and (4) _research dissemination._


## Research Questions (RQs)

- **RQ-1:** To what extent are community psychological theories and methodologies implemented, or not, in community psychology-based research related to intimate partner violence (IPV)?

- **RQ-2:** How has the implementation of community psychological research has evolved over time since the origination of the field, as well as potential trajectories based on the current state of discourse within Community Psychology and closely related research and practice disciplines?

\newpage

# References
