---
title: "**V.** Literature Review"
author: "Rachel M. Smith"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---

```{r setup, echo=FALSE, results='hide', fig.keep='none', fig.show='none', message=FALSE, warning=FALSE, cache=FALSE}
source("bibs.R")
knitr::opts_chunk$set(echo = FALSE)
```

\newpage\doublespacing

<!-- # V. Integrative Literature Description and Review -->

<!-- # V.1. IPV Interventions Research -->

As previously noted, the research reviewed here is conducted within a Community Psychological or closely related research framework and thus represents a subset of the available IPV-related empirical literature. The majority of the below-reviewed literature specific to evaluating IPV perpetration interventions were published in during or before 2008, whereas the subset of IPV-related research specifically inclusive of sexual minority women, reviewed in later sections, did not begin to emerge until 2005. Given this timeline and history, the review below provides details regarding the research methods and key findings from the set of earlier (i.e., published during or before 2008) evaluations of IPV perpetrator interventions. The first review is intended to provide an overview of the foundational research related to IPV interventions conducted within frameworks aligning with applied community-psychological theory and methods.

## IPV Perpetrator Intervention Program Evaluations


`r tufte::newthought("Brief History of U.S. IPV Perpetrator Interventions.")` Efforts to address violence against women and in particular intimate partner and sexual violence in the United States began with an overall focus on treatment and tertiary intervention approaches, which, understandably, were primarily focused on addressing the immediate needs of victims.<!-- CITE -->  Until IPV perpetration became a crime in all 50 states, these efforts were in large part initiated and sustained on "grassroots" levels, connecting with and building upon one another toward efforts to affect more large-scale changes at the policy and structural levels. The criminalization of IPV perpetration was eventually followed by the enactment and enforcement of mandatory arrest laws across the country, which, while varied in scope and levels of implementation, essentially require police officers responding to calls deemed characteristic of domestic violence impose some level of punitive action against the accused offender in the situation. These laws were created and continue to be enforced under the goal of ensuring victims' safety. The U.S. 1994 Violence Against Women Act shared a similarly victim-safety-centered purpose and, among a plethora of policy implications, was the first national-level policy providing at least a minimal amount of federal and state-level funding allocations specifically for developing and sustaining services for victims of IPV in each U.S. state.

During the same time period described above, work was also being done to address the issue of IPV perpetration, which ultimately led to the emergence of various programs and focused on tertiary and secondary levels of IPV prevention across the country [@tolman1995intervention]. Overarching approaches to IPV perpetrator interventions in the U.S. varied substantially throughout the late 1980s and through the early 2000s, and a majority of programs today have tend to follow a combination of approaches. For instance, cognitive behavioral therapy is often combined with the Duluth curriculum, which primarily targets intervention recipients' endorsement and internalization of patriarchal values of gaining and maintaining power and control over others [@price2009batterer; @pence1983duluth].

A common thread exists across the various approaches to IPV perpetrator interventions that is particularly relevant to the underlying purposes of the present review. As previously discussed, the IPV-related research foci of the late 1900s and early 2000s is beset aligned with the mainstream second-wave feminist movement in the U.S., as is the general focus of intervention and prevention efforts throughout the past several decades. As such, IPV perpetrator intervention approaches, such as the Duluth curriculum [@pence1983duluth] target heterosexual men's experiences, attitudes, and behaviors. Thus, while the underlying purpose of this review remains to inform IPV intervention and prevention efforts inclusive of sexual minority women, the available IPV interventions research, both within and outside of Community-Psychology and related disciplines, does not allow for any meaningful analysis of interventions with this specific population.

## Key Findings from Early Evaluations of IPV Perpetrator Intervention Programs

Using naturalistic observations<!-- of program practices --> and key informant<!--(i.e., program participants' current romantic partners)--> reports of IPV perpetrators' reassault rates `during the first`<!-- over the course of--> 15 months following their initial intake into the `intervention program`, @gondolf1999comparison provides a<!--`foundational`--> comparative evaluation of four IPV perpetrator intervention systems in four U.S. cities (i.e., Pittsburg, PA; Houston, TX; Dallas, TX; and Denver, CO).<!-- TODO: TOO LONG OF A SENTENCE--> Findings from this study are, however, somewhat mixed in that comparisons to evaluate differences in reassault rates across the four study sites, representing a continuum of least-to-most comprehensive IPV perpetration intervention systems, showed few meaningful differences across intervention sites.\ `Distinctions across the four sites are, however, more evident when individual perpetrator characteristics (e.g., psychopathology, substance abuse, previous arrests, etc.) and referral sources (e.g., court-mandated versus referral sources outside the court system) are also taken into account`. Further, while there was no significant effect of intervention site on reassault rates, the effect of the most comprehensive intervention system among the four included in the study `does tend toward significance`, particularly when this site's effect is compared with the least comprehensive intervention system included in this evaluation.

Overall, the total recidivism rate observed across all four programs evaluated in @gondolf1999comparison\'s investigation ($n_{total} = 656$) was 32% <!-- (_n_ = 210) --> for physical abuse and 43-70% for non-physical abuse (i.e., controlling behaviors, 45%; verbal abuse, 70%; and threats, 43%). In addition, 72% <!-- (_n_ = 343) --> partner respondents reported that they "feel 'very safe'" and 66% <!-- (_n_ = 281) --> indicated that they were "'very unlikely' to be hit". However, only 12% <!-- (_n_ = 54) --> rated their overall quality of life following their partners' completion of the intervention as "better", another 12% rated their quality of life as "worse", while 22% <!-- (_n_ = 100) --> rated their quality of life as the "same" as it was prior to their partners' intervention participation (p. 53).

Despite these mixed findings, @gondolf1999comparison\'s, relatively, early investigation into the possible differential effects of IPV perpetrator intervention systems representing four distinct points along a continuum from least-to-most comprehensive systems informs questions regarding system-, dyadic-, and individual-level factors that may influence these systems' efficacy at reducing reassault among men who have perpetrated IPV toward one or more female intimate partners. In particular, @gondolf1999comparison\'s findings regarding differences across the four intervention systems were most informative to understanding the effectiveness of IPV perpetrator programs when multiple levels of analysis are considered. That is, the effects of intervention systems' characteristics (i.e., comprehensiveness of services and intervention program length) on reassault rates appears `rather` sensitive to the inclusion of system-level variables not specific to the IPV perpetrator intervention itself (e.g., referral sources) and dyadic- and individual-level variables (e.g., victim-perpetrator contact during the 15-month study period, perpetrators' IPV-related and non-IPV-related criminal backgrounds, perpetrators' substance use or abuse, etc.) in each analysis.

The primary data source for @gondolf1999comparison\'s study's outcome variables is key informant reports provided by participating IPV perpetrators' current romantic partners, `regardless of whether those partners were` the original victims leading to the men's intervention program participation<!-- EDIT -->. This sampling and data collection method is an interesting approach to evaluating IPV perpetrator interventions, and the use of key informant reports (e.g., victims', current and/or past romantic partners', and intervention program facilitators' perspectives used as primary or secondary reports of program participants' behavior) is `somewhat thematic across a subset of subsequently-published literature included in this review`<!-- EDIT --> [e.g., @gregory2002effects; @silvergleid2006how]. `An additionally notable characteristic of` @gondolf1999comparison\'s `evaluation report` is the transparency with which the study's results are presented. While the evaluation ultimately provided, at best, mixed support for more the effect of more comprehensive IPV perpetration intervention systems, the results are presented such a way that acknowledge the state of this specific practice's field, which, at the time of the study's publication, is possibly best characterized as disjointed and in need of a more concrete and consistent evidence-base.

`In a separate effort to` inform the question of IPV perpetrator intervention effectiveness from the victims'/survivors' perspectives, @gregory2002effects conducted in-depth one-on-one interviews with 33 women identified via police reports as having experienced IPV victimization perpetrated by men referred to a local IPV perpetrator intervention program in a rural Ohio county. Interview questions sought information regarding the offenders' behaviors before, during, and after their participation in the intervention. Regarding survivors' accounts of offenders' behaviors prior to being referred to the intervention, the authors found that many of the men entering the intervention had also been physically violent with past romantic partners, close relatives, and male friends. In addition, a substantial proportion of survivor respondents indicated that jealousy, substance abuse, and family-related issues (e.g., issues related to children, finances, household chores, etc.) were apparent causes of conflict leading to the perpetrators' use of violence. Survivors' also provided insights into their assessments of more underlying causes of abuse, including issues related to power and control, their partners' low self-esteem, and conflict related to sexual/intimacy issues and the perpetrators' infidelity in the relationship. Regarding program participants' partners' accounts of the intervention's effectiveness, the majority of the 33 respondents in @gregory2002effects\'s evaluation indicated either a decrease or complete elimination of violence in their relationships, while a third of the partners reported that the intervention program in fact became a new source of conflict in their relationship, and 19% reported abuse during or following the offenders' program completion.

A particularly notable descriptive finding from @gregory2002effects\'s investigation is that, on average, over seven years lapsed between the first occurrence of IPV in the relationships accounted for by the study's survivor respondents and the IPV incident resulting in the perpetrators' referrals to the intervention program. Although not explicitly connected in the study's findings report nor discussion, this finding may inform survivor respondents' apparent consensus that jail time should be an immediate and/or unconditional sanction imposed against individuals found guilty and/or under investigation for IPV perpetration. Further, an average time-lapse of this magnitude indicates a potentially critical flaw in the implantation of any form of a coordinated community response to IPV [@hart1995coordinated].

@gregory2002effects\'s evaluation is restricted to female survivors' accounts of male IPV perpetrators court-mandated, either as part of post-sentencing probationary requirements or deferred-sentencing conditions, to complete the intervention, and therefore does not include accounts of the intervention programs' participants who are not referred to the program by the courts. @gregory2002effects\'s sample further excludes accounts of same-gender IPV perpetration or victimization, as well as IPV perpetrated by female-identified individuals toward male-identified partners. This sampling frame is similar to that defined in @gondolf1999comparison\'s investigation (summarized above) both in terms of the specific included and excluded populations, as well as the fact that the sampling restrictions in both studies are, at least to some degree, a function of the populations served by the study sites themselves. That is, at the time the studies were conducted, the intervention programs evaluated in both investigations provided IPV perpetrator intervention services only to male-identified individuals who perpetrated IPV toward female-identified partners.

@hendricks2006recidivism conducted a comparative evaluation of two IPV perpetrator intervention programs in a small metropolitan Wisconsin county [@ingram2012nchs]. Although @hendricks2006recidivism ultimately describes the programs evaluated their investigation as two independent interventions, one of the programs, _"Reasoning & Rehabilitation (R&R)"_ is in fact evaluated as a `sort of nested or secondary` intervention within the county's larger IPV perpetrator intervention system, _"Stopping Abuse for Everyone (SAFE)"_ (p. 704). That is, individuals are referred to the _R&R_ program `if they are determined as in need of` greater levels of supervision based on a clinical assessment administered during the _SAFE_ program's intake process. Such individuals are expected to return to and complete the _SAFE_ program's intervention after completing the additional _R&R_ program. @hendricks2006recidivism\'s investigation also included an evaluation of the predictive validity of the _Level of Service Inventory–Revised_ [_LSI-R_; @andrews1994level], which is the assessment administered to determine intervention participants' levels of risk and need at intake for the _SAFE_ program. Regarding the latter, results from logistic regression analyses provided minimal support for the LSI-R scale's accuracy, sensitivity, and specificity in correctly classifying recidivating intervention participants (overall classification accuracy = 66% correct). However, while formal logistic regression analysis was not similarly conducted to examine the measure's predictive accuracy regarding program placement, comparisons<!-- via between-subjects factorial--> via cross-tabulations and chi-square ($\chisq$) analyses revealed significant differences in both LSI-R scores and recidivism rates among intervention participants. Specifically, participants who completed the _SAFE_ program without referral to the _R&R_ program (14.4% recidivated) had significantly lower recidivism rates than those who completed both interventions (32.4% recidivated; $\chisq(1) = 6.26,~p < .05$). As @hendricks2006recidivism note, because participants were referred to the _R&R_ program on the basis of their LSI-R scores, these differences in recidivism rates do not necessarily inform comparisons regarding each intervention program's individual effectiveness at reducing or preventing future violence perpetration among participants. However, a possibly missing point in @hendricks2006recidivism\'s report and analytic conclusions is that these observed differences may provide support for the discriminant validity of the LSI-R as a measure effective in determining the relative risk and needs levels of IPV perpetration intervention participants.

In general, research on the effectiveness of IPV perpetrator intervention programs in the late 1990s and early 2000s, including the above-reviewed research, provides a mixture of evidence in favor and not in favor of these programs' effectiveness [@feder2005meta]. The above-reviewed subset of the IPV-related literature reiterates the general ambiguity regarding effective approaches to IPV interventions [@gelles2001standards; @dutton2006transforming; @gondolf2007theoretical; @dutton2007duluth]. Unfortunately, this ambiguity has persisted, as is evidenced by the continued mixed findings presented throughout the overall body of IPV-interventions-related literature [@eckhardt2013effectiveness; @arias2013batterer; @babcock2016domestic]. This ambiguity has often been interpreted over the years as an ultimately adverse outcome<!-- CITE--> such that the overall efficacy of IPV perpetrator interventions to prevent program participants' future IPV perpetration remains, at best, in question, and in some views non-existent [@dutton2006transforming; @dutton2007duluth]. However, such conclusions neglect attention to the full extent of the available evidence. It is crucial to consider that these interventions are in fact quite varied in terms of the underlying program theories, overall program structures, treatment modalities, and implementation [@gelles2001standards]. Further, the empirical community-psychology related literature reviewed above does provide some evidence that certain approaches to and components of IPV perpetrator interventions may be more effective than others [e.g., @gondolf1999comparison; @hendricks2006recidivism].

It is, therefore, important to explore the processes underlying successful outcomes (e.g., reduced or eliminated recidivism among participants) in these interventions. @silvergleid2006how provide one such exploration of the key processes facilitating positive change among men who successfully completed an IPV perpetrator intervention program in Portland, Oregon. @silvergleid2006how conducted in-depth, semi-structured, one-on-one interviews with ten intervention group facilitators and nine men who were within two-weeks of having completed their participation in the intervention and who were nominated by group facilitators. Four levels of change processes were identified through inductive thematic analysis of the interview data: (1) "community and extratherapeutic influences", (2) "organizational influences", (3) "group processes", and (4) "individual psychological development" (p. 144). The group-level processes seem especially influential in terms of facilitating a _process_ of change, in that this level of influence is further categorized into three sub-processes that appear to build from one another: (1) balancing support and confrontation, (2) sharing and hearing stories, and (3) modeling and mentoring. Facilitators' accounts further emphasized the group-level influences as instrumental in the process underlying intervention participants' "'resocialization' into a new manhood" [@silvergleid2006how, p. 151].

@contrino2007compliance quantitatively examined intervention program participants' levels of compliance with program requirements (e.g., attendance, engagement with the program, maintaining sobriety, nonviolence, etc.) and the extent to which participants retain key components of the intervention's content (e.g., power and control dynamics versus non-controlling behaviors). This investigation's focus aligns with @silvergleid2006how\'s qualitative findings regarding key influences underlying and facilitating IPV perpetrator intervention program participants' change processes. Specifically,<!--both program participant and facilitator --> interviewees in @silvergleid2006how\'s sample emphasized the importance of learning new skills (e.g., taking a 'time-out') and engagement with program activities (e.g., reading required texts, journaling, acknowledging their past violent behaviors and the impact of those behaviors on others, etc.) in the change processes experienced by program participants:

> "The most emphasized aspect of awareness was the participant’s new understanding of the effects of their abuse on others. For many men, truly sit- ting with that understanding, the devastating impact of their actions on those around them, was a strong impetus for change" (@silvergleid2006how, p. 153).

Findings from @contrino2007compliance\'s process evaluation somewhat reiterate the above-described processes and corresponding outcomes among intervention participants. For instance, @contrino2007compliance examined the differential effects of intervention participants' levels of compliance \edit{(high versus low)} with program expectation domains on the extent of participants' intake and internalization of the intervention, operationalized in @contrino2007compliance\'s analysis as recall of key components of the intervention's content (e.g., forms power and control). Participants' recall of power and control forms was found to vary as a function of four out of the ten assessed program expectation domains including (1) using techniques to avoid violence, (2) process-consciousness and communication skills, (3) self-disclosure<!-- of ones's feelings--> and non-defensiveness, and (4) use of respectful or sensitive language. However, domains including participants' sustained sobriety and nonviolence throughout their enrollment in the intervention, help-seeking, consistent program attendance, and active engagement in group sessions were not associated with the number of forms of power and control they were able to recall. The lack of effect of the latter two domains (i.e., program attendance and active engagement with the program) on participants' recall of intervention content is particularly interesting in light of the four domains for which such an effect was evident.

At a conceptual level, the above-listed four program expectation domains shown to influence intervention intake and internalization, appear thematically grouped as representing processes of change via internalization and application of the intervention. It seems logical that such change processes would coincide with being both physically and mentally present during the intervention itself. That no relationship was found among the attendance and engagement program expectation domains and participants' intake and internalization of the intervention is contradictory to these conceptual themes. The measure used to assess program expectation compliance is described in @contrino2007compliance\'s report as an adaptation of Edward Gondolf's "discharge criteria" [@contrino2007compliance, p. 1559]. The description provides limited information beyond the list of program expectation domains assessed, description of the 5-point likert-type response scale, and brief scoring information. Unfortunately, no sample items are provided for the original discharge criteria nor the adapted measure used in @contrino2007compliance\'s investigation, and the web address provided in the citation for Gondolf's original discharge criteria^[\url{http://www.mincava.umn.edu/papers/gondolf/discharg.htm}] does not appear to provide the original measure itself nor additional information regarding the measure's content.<!--, suggesting the content has migrated elsewhere since @contrino2007compliance\'s report was published.--> However, Gondolf's "discharge criteria" measure is provided by @gondolf2009clinician, along with details regarding its development, content, and usage with reference to its use in @contrino2007compliance\'s investigation. The _Discharge Criteria Form_ as published in @gondolf2009clinician is provided in \edit{Appendix [\todo]}. The measure assesses intervention participants' level of compliance with the previously mentioned program expectation domains via a single question per domain. This structure limits the assessment tool in terms of its ability to capture the range of qualities and behaviors it is intended to measure. For instance, the item assessing the active engagement domain is written in such a way that, most likely, could only reliably capture explicit behavioral displays of engagement, thereby potentially omitting information regarding active engagement among participants whose expressions of engagement in the program may be less extraverted or more introspective. This limitation may help explain the above-described conceptual discrepancies apparent in @contrino2007compliance\'s findings. The measure itself could be improved in terms of its general applicability and sensitivity to the diversities that may exist among IPV intervention participants adding additional items assessing varying forms of the target behaviors for each of the assessed domains.

The above-described IPV perpetrator intervention evaluation studies [i.e., @gondolf1999comparison; @hendricks2006recidivism; @gregory2002effects; @silvergleid2006how; @contrino2007compliance] was published in either the _Journal of Interpersonal Violence_ or _Violence Against Women_ \edit{(see Table [\todot])}.<!-- !!! TODO: tl.inv[, c(1, 4, 2)] !!! --> Each of these evaluations focuses on IPV perpetrator interventions best characterized at the tertiary level of intervention and prevention such that the overarching target population in each evaluated intervention program is comprised entirely of individuals who have perpetrated IPV at least once in their lifetimes and the primary purpose each intervention program is to prevent these individuals' future IPV perpetration. Importantly, each programs' target treatment population is restricted to adult men who have perpetrated IPV toward a female-identified intimate partner.

Interestingly, @price2009batterer\'s findings from a national survey of 276 IPV perpetrator intervention programs ($N = 45$ U.S. states represented in the sample) suggest that, although the vast majority of these intervention programs serve a ratio of male-identified to female-identified IPV perpetrators is 9:1, $74\%$ of respondents to @price2009batterer\'s survey indicated that they do offer programming for non-male-identified perpetrators, and 78\% offer programming for homosexual IPV perpetrators. Thus, the target population restrictions of the IPV intervention programs evaluated in the above-reviewed literature may not be representative of the typical target population restrictions across the U.S., but are nonetheless representative of the typical recipients of IPV perpetrator interventions across the country.

\newpage

# References
