# VI. Critique of Literature

Research conducted within the subset of community psychology focused around intimate partner violence was initially evaluated according to the level of inclusion and exclusion of the historically marginalized population of interest: sexual minority women (SMW). The implementation of action-oriented Community Psychology methodologies and analytic approaches will then be reviewed within each of these categories (i.e., inclusion or exclusion of SMW) in terms of (1) the appropriateness of the methods to the research question, (2) how the methods facilitated the inclusion or exclusion of sexual minority women, and (3) whether and how (where applicable) exclusion of sexual minority women is justified.

## Overarching Critique Criterion

`r tufte::newthought("Rigor in Action-Research Methods")`:

- Choice, description, justification, appropriateness, and execution of overarching methodology (i.e., quantitative, qualitative, or Mixed-Methods), sampling frame definition, sampling and data collection methods, and analytic approaches.
- Interpretations of results, limitations, results interpretations.
- Presentation, dissemination, application, and accessibility of the research.
- Transparency and reproducibility of the research methods, findings, and limitations

`r tufte::newthought("Stakeholder Input.")`:

- Are efforts made to ensure that _all available_ stakeholders' and informants' voices and accessibility considered equally, and that certain voices are not unjustifiably privileged over others?
- Are primary and distal stakeholders and informants to the research given access to reports of a given project's progress and/or findings? Is such access in fact accessible (i.e., free and easy to locate)?

`r tufte::newthought("Interpretations of Findings.")`

- Is feedback from key stakeholders and informants to the research accepted and genuinely considered by the core research team?
- Are efforts made to ensure that _all available_ stakeholders' and informants' voices and accessibility considered equally, and that certain voices are not unjustifiably privileged over others?

`r tufte::newthought("How the methods facilitate the inclusion or exclusion of specific populations")`

- Whether and how exclusion of specific populations is justified (if applicable)

`r tufte::newthought("How the methods facilitate the inclusion or exclusion of \\textit{sexual minority women}")`

- Whether and how exclusion of _sexual minority women_ is justified (if applicable).



## Methodologies & Methods Utilized

The majority of the reviewed studies follow quantitatively-based methodologies (n = 14; 61%), with just over a quarter (n = 6) employing qualitatively-based methodologies, and only four studies utilizing mixed-methodological approaches. Of the reviewed quantitatively-based studies, 86% (n = 12) employed experimental and/or longitudinal, rather than cross-sectional, designs. All but one of the quantitative studies (93%) used self-report survey measures as the primary datasource. Four of the six qualitatively-based studies used group interviews as the primary data collection method, one administered and analyzed responses to a qualitative self-report survey, and one employed a multi-method qualitative approach. The methods represented among studies following mixed-methodological designs include experimental and longitudinal mixed-methods, focus groups, and qualitative and quantitative self-report measures.

## Populations Included/Sampling Frames

## `Explicitly` Excluded Populations

## _A. Strengths_ \todot


## _B. Limitations_ \todot
