---
title: "A Methodological Review of Community-Based Research Related to Intimate Partner Violence"
author: "Rachel Smith-Hunter"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---


## Presentation Agenda {.shrink}

- \textsc{\textcolor{dkblue}{Introduction}} <!-- Part I. -->
    - Research Questions
    - Rationale
    - Guiding Community-Psychology Theoretical Frameworks

- \textsc{\textcolor{dkblue}{Systematic Literature Search \& Review Methods}} <!-- Part II. -->
    - Analytic Approach
    - Initial Literature Screening, Assessment, \& Organization
    - Synthesis & Methodological Evaluation

- \textsc{\textcolor{dkblue}{Literature Synthesis \& Review}}  <!-- Part III. -->
    - Summative Characteristics of the Included Literature
    - Sampling Frame Definitions and Sampling Methods
    - Methodologies & Methods Utilized
    - Ecological Levels of Analysis Reflected in the Literature
    - IPV Perpetration Interventions
    - Perpetrator Intervention Programs' Efficacy
    - Processes of Change
    - Public Policy & Program Practices
    - Prevention-Oriented IPV Intervention Programs
    - IPV Prevention Program Implementation & Evaluation Methods
    - Assessing Risk of IPV among Sexual Minority Women
    - Police Responses to Same-Gender IPV

- \textsc{\textcolor{dkblue}{Summative Methodological Critique}} <!-- Part IV. -->
    - Ecological-Validity

- \textsc{\textcolor{dkblue}{Discussion}} <!-- Part V. -->
    - Limitations of This Review
    - Implications

# Introduction <!-- PART I. -->

## Rationale

`r tufte::newthought("Intersecting Community-Psychology Theory \\& Research Methodology")`

## Guiding Community-Psychology Theoretical Frameworks

`r tufte::newthought("Ecological systems theory and the Social Ecological Model")`

`r tufte::newthought("Protective (versus risk) Factors")`

`r tufte::newthought("'The inextricable relationship of empowerment and politics'")` **[@riger1993what, p. 283]**.


# Systematic Literature Search \& Review Methods <!-- PART II. -->

## Analytic Approach

### Initial Literature Screening, Assessment, \& Organization

### Synthesis & Methodological Evaluation

`r tufte::newthought("Defining and Evaluating Methodological Rigor")`


# Literature Synthesis \& Review <!-- PART III. --> {.shrink}

## Summative Characteristics of the Included Literature

### Sampling Frame Definitions and Sampling Methods

### Methodologies & Methods Utilized

### Ecological Levels of Analysis Reflected in the Literature

`r tufte::newthought("Substantive Research Topics at Varying Levels of Ecological Analysis")`

## IPV Perpetration Interventions

### Perpetrator Intervention Programs' Efficacy

### Processes of Change

### Public Policy & Program Practices

## Prevention-Oriented IPV Intervention Programs

### IPV Prevention Program Implementation & Evaluation Methods

## IPV Research Specifically Inclusive of Sexual Minority Women

### Assessing Risk of IPV among Sexual Minority Women

`r tufte::newthought("IPV Risk Factors, Causes, \\& Consequences among Sexual Minority Youth")`

### Police Responses to Same-Gender IPV


# Summative Methodological Critique <!-- PART IV. -->

### Ecological-Validity

### Limitations of This Review

### Implications

# References {.allowframebreaks}
\refs
