---
title: "$\\mathpzc{VI.}$ Critique of Literature"
author: "Riley M. Smith"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---


# Overarching Critique Criterion

1. Rigor in Action-Research Methods
    - Research question(s) and/or hypothesis(es)
        - Appropriateness of the methods to the research question(s) and/or hypothesis(es)
    - Appropriateness of the methods to the population
        - Sampling frame definition
    - Data collection modality/modalities
    - Analytic approach \& procedures
    - Presentation \& Interpretation(s) of results
    - Limitations description, interpretation, and justification
    - Application \& dissemination of research and findings
2. How the methods facilitate the inclusion or exclusion of specific populations
    - Whether and how (where applicable) exclusion of specific populations is justified.
3. How the methods facilitate the inclusion or exclusion of _sexual minority women_
    - Whether and how (where applicable) exclusion of _sexual minority women_ is justified.
