---
title: "My perspective as a researcher"
date: "2013-12-2"
---
This program of research is ultimately aimed at addressing IPV within same sex female-identified couples. This definition of the population is not trans* exclusive, rather, we are interested in evaluating the dymnamics of romantic couples comprised of two people who identify as women. This will necessarily lead to separations in the data such that couples who involve one or both trans* individuals will probably need to be evaluated separately from cis-gender couples. As this program progresses, I will eventually want to include ALL couples who have ever, or who may ever (e.g., people in transition), identify as women.

As a researcher, my perspective has multiple dimensions. First and foremost, I identify as a feminist researcher. This political identity, despite its limited label, involves, at the forefront, the notion that people, regardless of gender, deserve to be treated equally, and without the threat of violence – in whatever form that involves (e.g., physical, psychological, economic, etc.). An additional important identity of mine is that of a cis-gender, white, middle-class lesbian. This identity affords me a considerable amount of privilege, especially within my population of interest. I recognize that this perspective is limited, and thus the results of this research should be understood within this limited framework. At the same time, I have worked with, and continue to work with, populations that encompass a variety of alternative and informative perspectives to my own, and these experiences have helped to develop a more well-rounded perspective for myself.
