---
title: "Thoughts on Terminology and the Processes of Oppression"
date: "2014-05-20"
---

Sexual and gender identities that necessarily reject the dominant ideology of **hegemonic heterosexuality(ism?)** (I.e., sexual and gender minorities) foster a sense of community that is based in non-conformity. Conceptually, this sense of community should be characterized as a "safe space", yet, within the context of this marginalized community certain norms, likely mirroring the context of the overarching hegemonic group (I.e., whiteness and dominant masculinity) rise to the top of the social capital ladder and become the new hegemony for that environment (space?). Resulting from this are stereotypes applied from the overarching out group (I.e., **hegemonic heterosexuality**(ism?)) toward the targeted (marginalized) group and stereotypes applied from the dominant group with the marginalized group (**marginalized dominant group**?) to **intersectionally marginalized** groups and individuals within the **overarching target group of sexual and gender minorities**.
