---
title: "Short Lit Review: FSSIPV"
date: "2014-04-10"
---

Intimate partner violence among female-identified partners is slowly becoming recognized as a real issue that affects many lives. While historical data is less available than for rates of heterosexual intimate partner violence (IPV), recent data suggest that lesbians experience IPV at similar rates of heterosexual couples (Black et al., 2010). The lack of research related to female same-sex IPV (FSSIPV) has been primarily attributed to gender role stereotype expectations of women to be nonviolent, or the notion that women do not possess the ability to be violent or violent enough to inflict pain on others (Hassouneh & Glass, 2008; Little & Terrance, 2010; Mitchell, 2008). Because of the lack in empirical research related to the causes of FSSIPV, much of the available research seems to focus primarily on two themes surrounding the phenomenon: (1) simply reporting rates of FSSIPV, and/or (2) perceptions of gender role stereotypes from heterosexual groups/individuals about lesbian relationships, and the possibility of violence in those relationships (McClennen, 2005, Messinger, 2011). Interestingly, unlike research related to IPV within heterosexual relationships, very little research has examined, whether theoretically or empirically, the link between gender roles, gender norms, and gender identities within same-sex female-identified relationships and FSSIPV.
