---
title: "A Methodological Review of Community-Based Research Related to Intimate Partner Violence"
author: "Rachel Smith-Hunter"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---

\part{Introduction} <!-- Part I. -->

# Rationale

# Guiding Community-Psychology Theoretical Frameworks

\part{Systematic Literature Search \& Review Methods} <!-- Part II. -->

# Analytic Approach

## Initial Literature Screening, Assessment, \& Organization

## Synthesis & Methodological Evaluation

\part{Literature Synthesis \& Review} <!-- Part III. -->

# Summative Characteristics of the Included Literature

## Sampling Frame Definitions and Sampling Methods

## Methodologies & Methods Utilized

## Ecological Levels of Analysis Reflected in the Literature

# IPV Perpetration Interventions

## Perpetrator Intervention Programs' Efficacy

## Processes of Change

## Public Policy & Program Practices

# Prevention-Oriented IPV Intervention Programs

## IPV Prevention Program Implementation & Evaluation Methods

## Assessing Risk of IPV among Sexual Minority Women

## Police Responses to Same-Gender IPV

\part{Summative Methodological Critique} <!-- Part IV. -->

## Ecological-Validity

\part{Discussion} <!-- Part V. -->

## Limitations of This Review

## Implications

# _**Epilogue:**_ _Reflections on the Unique Challenges of Conducting a Community-Psychology-Focused Systematic Literature Reviews_

# Appendices
