# Limitations of This Review

The present review is specifically focused on the methodological quality of research conducted within the aforementioned frameworks and the corresponding implications for IPV-related research and intervention practice specific to sexual minority women. The lack of available empirical literature evaluating IPV-related interventions specifically inclusive of sexual minority women at the time this review was conducted posed an inherent limitation to the overall content of the present review. In addition and as previously noted (see _"Systematic Literature Search & Review Methods"_), the present review is confined to IPV-related interventions research conducted (a) in the United States and (b) within Community-Psychological and closely related research frameworks, and therefore does not provide a synthesis nor methodological evaluation of full body of available IPV-related research. The latter limits of this review cause a second limitation, which is that this review does not provide a systematic comparative analysis of U.S.-based IPV-related research conducted within Community Psychological frameworks versus research conducted outside of (a) the United States nor (b) Community Psychological research frameworks.

A key to addressing these limitations is the continued burgeoning of IPV-related research that is specifically inclusive of lesbian, gay, bisexual, transgender, and queer populations. It is crucial that this growing body of research actively works to avoid the same limitations consistently found across research conducted under the goals of alleviating social and public health issues such as intimate partner and sexual violence. Specifically, the growing IPV-related literature, both within and outside of Community Psychology and related disciplines would benefit from more reflexivity in terms of the intersections between the research methods, tools, analytic approaches we learn, adapt, and employ and the populations and contexts that are either over- or under-represented in our research. 
