# Abstract

This systematic methodologically-focused review maps core components of community psychological theory and methodologies to the currently available intimate partner violence intervention and prevention research conducted within community psychological and closely related research disciplines. Community psychological theory values the notion that the communities in which research is taking place and/or affecting (whether directly or indirectly) should be as involved as possible in all phases of the research process, rather than solely as anonymous data points in the analysis. Community psychology thus favors inclusion over exclusion, participant voices equally with researchers' voices, and participatory and/or purposive sampling methods over convenience sampling methods. The reviewed literature will be evaluated and critiqued according to these types of community psychological standards regarding (1) _research methodologies_, (2) _data analytic approaches_, (3) _interpretations of findings_, and (4) _research dissemination._ This review evaluates the extent to which community psychological theory and methodologies are and are not implemented in community-based research related to intimate partner violence. The review specifically follows the methodological evolution and diversity methods and data analytic approaches over time since the origination of Community Psychology as a research discipline, as well as potential trajectories based on the current state of discourse within Community Psychology and closely related research and practice disciplines.
