\doublespacing

# Reflections on the Process of Writing this Review

At multiple junctures in the development of this review questions and suggestions along the lines of "Why not broaden the scope to include sexual minority _men_", or "perhaps remove the focal population restriction from the review's scope altogether". The present review was, in a sense, deliberately poised by the author to potentially fail in finding an adequate body of literature covering the present review's primary substantive research topic. That is, having spent several years researching IPV-related topics specific to sexual minority women within community-psychology-specific frameworks, the author was quite aware of the overall dearth of empirical research conducted on this specific topic that is specific to the author's population of interest. The rationale and justification for attempting to conduct a systematic review of a body of literature that most likely, and in fact, does not exist lies in the author's `{! desire !}` to better understand _why_ the particular subject of women's use of violence in their same-gender romantic relationships remains a consistently lacking area of research. This is particularly justified in light of the long awaited-for validation of what was likely already known by a majority of members of the sexual minority women community, in general, which is that IPV does in fact exist among us and in our community. It can be a bit of a tough pill to swallow, so to speak, but is nonetheless, in the author's experience, a typically known fact within SMW communities that IPV is perpetrated and experienced among our community members as much as, if not more than, it is among our brothers in the sexual minority male communities, as well as among heterosexual communities. The silence around the topic of IPV perpetrated by sexual minority women, however, is what most intrigues this researcher. What facilitates this silence? It is a fallacy to assume the silence is maintained primarily by the community itself, as researchers within or closely tied to the SMW community, such as Claire Renzetti [@renzetti1992violent], Janice Ristock [@ristock2002no], and Ruthann Robson [@robson1990lavender], have published, relatively, extensively on the subject over the past few decades. Yet it remains that _no_ empirical research regarding IPV intervention nor prevention approaches appropriate for, relevant to, nor specifically inclusive of sexual minority women has been conducted by the very research field found on principles of diversity and innovation in research methodologies [i.e., Community-Psychology; @fine2003participatory; @balcazar2004participatory; @maguire1987doing]

\newpage

# References
