---
title: "A Methodological Review of Community-Based Research Related to Intimate Partner Violence"
author: "Rachel Smith-Hunter"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---

# Introduction <!-- Part I. -->

## Rationale

## Guiding Community-Psychology Theoretical Frameworks

# Systematic Literature Search \& Review Methods <!-- Part II. -->

## Analytic Approach

## Initial Literature Screening, Assessment, \& Organization

## Synthesis & Methodological Evaluation

# Literature Synthesis \& Review  <!-- Part III. --> {.shrink}

## Summative Characteristics of the Included Literature

## Sampling Frame Definitions and Sampling Methods

## Methodologies & Methods Utilized

## Ecological Levels of Analysis Reflected in the Literature

## IPV Perpetration Interventions

## Perpetrator Intervention Programs' Efficacy

## Processes of Change

## Public Policy & Program Practices

## Prevention-Oriented IPV Intervention Programs

## IPV Prevention Program Implementation & Evaluation Methods

## Assessing Risk of IPV among Sexual Minority Women

## Police Responses to Same-Gender IPV

# Summative Methodological Critique <!-- Part IV. -->

## Ecological-Validity

# Discussion <!-- Part V. -->

## Limitations of This Review

## Implications
