---
title: "Place-Based Methods - Reading Notes"
author: "Rachel M. Smith"
date: "Winter, 2016"
---

# @proshansky1983place

In their discussion of the _Anxiety and Defense Functions_ of place-identity, @proshansky1983place assert that "... persistent cognitive discrepancies between physical setting properties and place-identity expectancies may foster feelings of threat and pain in association with those cognitions which in turn motivate the person to avoid this setting. Reactions of this kind will often occur in the formative years but are clearly not limited to childhood." (p. 73) I am curious about the effect of such discrepancies occurring at a slightly more distinct level with two particular components: (1) prolonged (i.e., far beyond the formative developmental years) experiences of cognitive discrepancies related to one's place-identity, and (2) discrepancies that occur in places or spaces, or in close association with either, to which an individual feels she is either supposed to belong based on one or multiple facets of her identity. In less abstract terms, I am thinking specifically about my research on lesbian, bisexual, transgender, and queer (LBTQ) women and girls, and experiences of marginalization _within_ LBTQ-specific spaces and places. While my focus until about six months ago has been intersectionally-based, I've recently realized through conducting interviews with other LBTQ women that my intersectional focus has been limited to the individual personality and demographic (for lack of a better word at the moment) facets of identity without taking into account the intersections that exist among places, spaces, and individual identities.

# @lewicka2011place

Interestingly, the @lewicka2011place discusses findings indicating that research has found the presence of diversity to be negatively related to place attachment, community cohesion, interpersonal trust, etc. However, I wonder if the same is true for a lack of diversity. Thinking of my own experiences and Portland's overwhelming lack of racial diversity, and the continued issues of gentrification across the city, I have often found myself lacking in a sense of community tied to Portland and part of that has been because I am a bit hyperaware of the fact that I am more often than not interacting with people that look a lot like me (in terms of race, socio-economic status, and age). My hyperawareness of this dynamic is, in my own analysis, in large part due to the fact that people that look like me tend to carry with them a lot of privilege, especially in Portland, OR. I wonder, then, if there is another factor involved in the relationship(s) between diversity and place attachment. In particular, I wonder what historical socio-political factors might be useful in this particular realm of analysis in place research.

# @mcmillan1986sense

In the thirty years since this article was published, we have witnessed several manifestations, both here in the U.S. and globally, of the "potential for great social conflict" [@mcmillan1986sense, p. 20] resulting in part from increased senses of community among relatively small, but loud, organized communities. We have also seen a great deal of technological advancements, particularly in terms of the people's ability to create, foster, and join communities online as well as in person. What implications do these historical dynamics have for community psychologists in terms of understanding sense of community as it manifests in our world today, as well as the application of that understanding?

# @pretty2003sense

In their examination of discriminate factors associated with dimensions of sense of community @pretty2003sense found age as a potential key factor. The authors assert that "This implies that there are other aspects of community sentiment not included here which are important to an adolescent’s feeling that ‘this town is the place for me’. Alternatively this finding may indicate that other objective dimensions of a community, such as its economic opportunities, may be more instrumental to identity during the adolescent life stage" (p. 283). Is there also a possibility that the social and physical environments in either or both of the study's settings could have underwent or were currently undergoing changes in terms of the people joining or leaving the communities? How might the introduction or loss of community members in these relatively small and rural places also impact adolescents', versus adults', senses of community?

# @stokols1992establishing

I appreciated @stokols1992establishing discussion of public policy implementation and I am curious how can we write and effectively implement legislation that is more primary prevention focused in its emphasis on the actual root causes of whatever is being prevented?

# @kloos2009social

I appreciated @kloos2009social emphasis on the importance of the interaction between individuals and their immediate home/housing environment. In thinking about housing for individuals with serious mental illness that is integrated within the surrounding neighborhood or community, I was reminded of a soon-to-be opened school specifically for lesbian, gay, bisexual, transgender, and queer (LGBTQ) youth in Atlanta, GA. I've struggled a bit in deciding on my opinion about this particular school because it seems that the intended benefits of such a school (i.e. Safety for LGBTQ youth) is being sought at the expense of community integration. What are the potential negative consequences of disintegrating marginalized populations from their surrounding social environments?

# @wright2007housing

@wright2007housing argue, and in my opinion provide sufficient evidence through their findings, that individuals' perceptions of their immediate physical environment impacts individuals their experiences within those environments. I am curious, however, about the intensity, rather than immediacy, of individuals perceptions of their environments. What is the potential effect of differentially intense perceptions of more distal aspects of an individual's setting?

# @shinn2003community

@shinn2003community assert that "Diverse groups may feel differentially accepted and supported in the same setting" (p. 443). In the examples that follow this assertion, the authors cite research findings regarding LGBTQ individuals' experiences of marginalization in certain settings despite heterosexual individuals' perceiving the same settings as open to and accepting of LGBTQ individuals. I am once again reminded of within group marginalization among marginalized populations. Is it possible that settings that being in setting that is experienced as marginalizing by a whole group overshadows the potential experiences of marginalization within that group?

# @nicotera2007measuring

@nicotera2007measuring provides a sort of spectrum of conceptualizations of the neighborhood construct ranging from more rigid definitions toward more flexible conceptualizations. The fourth definition listed in Table 1 (p. 30), in my view, represents the latter end of this spectrum. As I continued through the paper, I was left with these questions: (1) What are the potential benefits and drawbacks of having a more flexible definition of neighborhood? (2) How does a flexible versus more rigid definition (and vice-versa) of neighborhood benefit applied psychological research?

# @sullivan2006assessing

In discussing his study's findings @sullivan2006assessing argues that the study contributes to the current body of relevant research literature by "accurately measuring the level of neighborhood support for gentrification using survey data, probability sampling, and a large sample" (p. 617). I was genuinely surprised to see this the first of two contributions the study's findings makes to research on neighborhoods and gentrification given that the measurement of residents' attitudes toward ongoing gentrification processes in the Alberta Street neighborhood was precisely where I felt the author did not provide sufficient detail in explaining the study's methods. Based on the author's descriptions of the measures used for this study, which provides very little in the way of how the interview questions were derived and the reliability and validity of the items used to measure each of the study's variables, I would argue that resident's attitudes were somewhat, but not entirely, adequately measured based on the set standards of reliability and representativeness in terms of quantitatively measuring a thing, but that this is not necessarily an accurate measure of residents' attitudes given that the author does not sufficiently defend the validity of measures' content.

# @sullivan2011retail

One of the longtime critiques of gentrification is that it is a process that tends to displace already marginalized groups within a given setting. That ongoing marginalization process works primarily by silencing the voices of the longtime residents of the area being gentrified in favor of elevating the voices of the gentrifiers, who, as discussed by both @sullivan2006assessing and @sullivan2011retail, tend to be representative of more affluent/dominant social and economic classes. I find it interesting, then, that both @sullivan2006assessing and @sullivan2011retail focus primarily, if not exclusively, on black and white residents in the Alberta Street neighborhood. Who's voices are silenced and what identities are ignored in their analyses as a consequence of their relatively limited sampling frame?

# @thomas2015crosstown

I appreciated @thomas2015crosstown's discussion of their findings around creative tensions: "creative tensions emerged around different notions of community and different ways of understanding art. … These two visions of community illustrate the tensions in place-making as a project that occurs across multiple levels and is framed in contested ways" (p. 80). This case study, and the authors' analysis of the effects on the immediately surrounding community of creating an arts community center, reminds me of a "grass roots" community arts and restoration movement that began a few years ago in the Edgewood, Old Fourth Ward, and Reynoldstown neighborhoods of Atlanta, GA. Collectively, these three particular neighborhoods happen represent one of the epicenters of the U.S. Civil Rights Movement during the mid-1900s (Dr. Martin Luther Kind Jr.'s childhood home and Ebenezer Baptist Church are both located near where the Edgewood and Old Fourth Ward neighborhoods converge). When this community arts and restoration movement, called "Living Walls", began I was a young college student with a hunger for social justice activism attending Georgia State University (which is located adjacent to the Edgewood Neighborhood), had lived in various spots within the Edgewood and Old Fourth Ward neighborhoods, and spending more than a fair amount of time at my favorite coffee shop located in Reynoldstown. I was also a stereotypically white social activist with a still relatively limited understanding of intersectionality. So, I thought the movement was "super cool!". It was not until my partner at the time called the movement "exceedingly pretentious" that I realized what was actually going on with this movement: a bunch of people with both social and economic influence were promoting their view of what was positive artistic expression at the expense of damning the use of "typical" graffiti in these neighborhoods. As time went on, I chose not to participate directly in the movement, and instead watched and listened to my friends who ended up standing on either side of it (i.e., those friends who actively participated in the movement and those who actively resisted it). What I ended up realizing was that the "typical" graffiti that the movement's leaders had deemed to be a negative aspect of the community was in fact the exact opposite to the community's longterm inhabitants.

@thomas2015crosstown's observations around creative tensions, and the effects of those tensions on place-making as well as on community members' differential senses of community, resonated quite saliently with my own, non-research-based experiences of observing similar community building and restoration efforts in Atlanta, GA. For me, my own experiences coupled with my experience reading @thomas2015crosstown's case study highlight the importance of anticipating, understanding, and appropriately reacting to the potential negative consequences of social activism and action research endeavors.

# @wang1997photovoice

@wang1997photovoice quite appropriately, in my opinion, argue that "The participatory process attempts to address material and status inequalities, yet the extent to which it may perpetuate those inequalities deserves scrutiny" (p. 374). I agree. However, the authors later discuss the capacity building element of photovoice (see p. 375). First, I was intrigued by this particular element, because I had never really considered photovoice as a method involving any sort of capacity building. Based on @wang1997photovoice description, photovoice as part of needs assessment efforts makes sense as a potentially capacity building tool for community action; however, I could not help but remain skeptical, given that the participants in the authors' example were given tools that facilitated the formation of the Provincial and County Guidance Group in Yunnan, and those tools were provided by researchers. That's really great and all, but I worry about what happens when the researchers, and the various power and privileges they represent and bring with themselves, leave or move on to other interests. To what extent does providing a set of tools to the members of a community remove or address issues of power and privilege, particularly power and privilege among those who provided the tools (i.e., the researchers)?

# @smith2015rebuilding

In their overview description of the themes found among participants' photographs @smith2015rebuilding note that female participants, who represent less than 20% of the study's sample, took the majority of photos of people, and that all of the people in those photos were those with whom the participants had close interpersonal relationships. I found this particularly interesting given that the sub-sample size of female participants was rather small (which I understand is likely a function, at least in part, of the distribution of males and females in the study's target population), and yet these participants' photographs represented a majority theme distinguishable from themes represented in the men's photographs. I wonder if there is something here (for future directions perhaps) in terms of the potentially differential importance of social/interpersonal relationships among men and women. Social psychological research, as well research from clinical and counseling psychology, has found significant evidence that men are socialized to adhere to specific masculine gender roles, one of which is extreme self-reliance [e.g., @levant2010evaluation; @levant2007review].

In light of @smith2015rebuilding other findings related to the emphasis on economic well-being among participants (e.g., having one's own apartment, future job possibilities/hopes, etc.), I think there might be room for future research to examine how the construct of place intersects with individuals' gender role socialization and gender role adherence.

# @case2014ethnography

There is this saying among academics that "research is me-search", usually referring to the idea that the phenomena researchers choose to examine most closely are those with which they have some close personal experience or investment. I was reminded of this saying when reading @case2014ethnography description of the tension in ethnographic research within community psychology around "Optimal Levels of Engagement" (p. 65). I was not, however, thinking of researchers' personal experiences with or investments in their chosen phenomena of interest, but really the fact that there is very difficult to actually remove the researcher from the research. In thinking further on this, I was also reminded of Grounded Theory research and analytic methods, and the emphasis within this method on the investigator's interpretation of the data as one of the main building blocks in theory development. I wonder, then, the issue of optimal levels of engagement away might be in part resolved/addressed by researcher's intentionally explaining their experience engaging a given context in their research and the potential meaning of that engagement in terms of their findings.

# @dutta2016ethnographic

@dutta2016ethnographic provides a really nice explanation and illustration of how research cannot be removed or realistically considered objectively separate from the researchers of any given phenomenon. While the purpose of @dutta2016ethnographic chapter seems primarily illustrative, thus the emphasis on the researcher's impact on his research and vise-versa, I wonder how researchers conducting non-ethnographic inquiries could incorporate information or reflections in the write-up of a given study about their role and impact on their researched phenomena, research participants, and the context(s) surrounding their research.

\newpage

# References
