Using naturalistic observations of program practices and key informant (i.e., program participants' current romantic partners) reports of program participants' reassault rates over the course of 15 months following program participants' initial intake into each intervention, @gondolf1999comparison provides a foundational comparative evaluation of four IPV perpetration intervention systems in the U.S. Findings from this study are, however, somewhat mixed in that comparisons to evaluate differences in reassault rates across the four study sites, representing a continuum of least-to-most comprehensive IPV perpetration intervention systems, showed few meaningful differences across intervention sites. Further, while there was no significant effect of intervention site on reassault rates, the effect of the most comprehensive intervention system among the four included in the study tends toward significance.

Despite these mixed findings, @gondolf1999comparison's, relatively, early investigation into the possible differential effects of IPV perpetrator intervention systems representing four distinct points along a continuum from least-to-most comprehensive systems informs questions regarding system-, dyadic-, and individual-level factors that may influence these systems' efficacy at reducing reassault among men who have perpetrated IPV toward one or more female intimate partners. In particular, @gondolf1999comparison's findings regarding differences across the four intervention systems were most informative to understanding the effectiveness of IPV perpetrator programs when multiple levels of analysis are considered. That is, the effects of intervention systems' characteristics (i.e., comprehensiveness of services and intervention program length) on reassault rates appears `rather` sensitive to the inclusion of system-level variables not specific to the IPV perpetrator intervention itself (e.g., referral sources) and dyadic- and individual-level variables (e.g., victim-perpetrator contact during the 15-month study period, perpetrators' IPV-related and non-IPV-related criminal backgrounds, perpetrators' substance use or abuse, etc.) in each analysis.

In addition the primary data source for @gondolf1999comparison's study's outcome variables is the participating IPV perpetrators' current partners, regardless of whether those partners were the original victims leading to the men's participation in the intervention program. This sampling and data collection method is an apparent theme across the subsequently-published literature reviewed below.

Finally, a notable characteristic of @gondolf1999comparison's evaluation report is the transparency with which the study's results are presented. While the evaluation ultimately provided, at best, mixed support for more the effect of more comprehensive IPV perpetration intervention systems, the results are presented such a way that acknowledge the state of this specific practice's field, which, at the time of the study's publication, is possibly best characterized as disjointed and in need of a more concrete and consistent evidence-base. 

\newpage
# References
