# (D) Relevance to Dissertation Topic <!--`(1 page)`-->

The proposed review paper is motivated by the program of research I have pursued over the past three years. I intend to continue pursuing this program of research via my dissertation. This program of research is focused on developing comprehensive and intersectional intimate partner violence (IPV) prevention strategies specific to the experiences and needs of historically marginalized populations.

## Dissertation Topic Background

My Masters thesis project served as the first phase of this research program. The purposes of this study were to (1) inform the finalization of a working intersectional model of same-gender IPV among sexual minority women, and (2) evaluate the face, construct, content validity, and coverage of existing survey measures related to the model's constructs in terms of their relevance and accuracy to sexual minority women's experiences and identities. A series of in-depth semi-structured, open-ended one-on-one interviews (n=10) and one focus group (ngroup=4) were conducted with fourteen lesbian, gay, bisexual, transgender, and queer (LGBTQ) women in Portland, Oregon. Individuals were recruited and engaged in the study via a combination of purposive and convenience sampling methods aided by involvement of multiple community partners working in violence and education related fields. Interview and focus group questions addressed participants' experiences with gender role stress and minority stress. Grounded theory analysis of participants' narrative responses informed the coverage and relevance of constructs in a working intersectional model predicting women's use of violence in their same-gender intimate relationships. Findings from this analysis support an intersectional and contextually-minded approach to IPV intervention and prevention strategies.

## Intended Dissertation Research

The first exploratory phase's findings and corresponding conclusions will directly inform the work for my dissertation, which will constitute the second phase of this research program. Specifically, I will use insights gained from this first phase of of research to make necessary revisions to the evaluated survey measures, and the modified measures will be used in the second phase of research to collect data from 200-300 LGBTQ women recruited from the greater Portland, OR area. The intersectional model will be subsequently tested for fit using these data, and findings from this second phase will be used in collaboration with local community partners to develop strategies for IPV intervention and prevention specifically tailored to the experiences, identities, and needs of LGBTQ women.

## Proposed Review Paper's Relevance

The theoretical and methodological groundings for the proposed review paper have and continue to serve as guiding frameworks for the above-described program of research. Further, the proposed critical review of community psychological theory and methodology applications aligns with the critical review I conducted as part of my Masters Thesis, which focused on the influence and consequences of second-wave feminism on IPV-related research, activism, policy, and practice. Through the latter critical review process, I developed a comprehensive understanding of the context in which the research area I am pursuing is situated. Similarly, I intend to utilize the proposed review paper as an in-depth critical reflection on the community psychology-specific context in which my dissertation research will be conducted.
