# (A) Completed Foundational Coursework \complete

`r tufte::margin_note("\\textit{Note: '\\textsuperscript{*}' denotes courses applicable to both the major and minor areas.}")`

```{r maj}
maj <-
    data.frame(
        CRN = c("`PSY 610`",
                "`PSY 614`",
                "`PSY 610`",
                "`PSY 510`"),
        Title = c("_Top: Community \\& Social Interventions_",
                  "_Advanced Applied Social Psychology \\& Community Psychology_",
                  "_Top: Program Evaluation",
                  "_Top: Place-Based Research"),
        Grade = c("B+",
                  "A",
                  "A",
                  "A"),
        Hrs = rep(4, 4),
        Term = c("Fall 2013", 
                 "Spring 2014", 
                 "Fall 2014", 
                 "Winter 2016"))

knitr::kable(maj, caption = "**Major Area Coursework**: Applied
      Social \\& Community Psychology",
      col.names = c("CRN",
                    "Title",
                    "Grade",
                    "Credit Hours",
                    "Term"),
      align = c('c', 'l', 'c', 'c', 'l'))
```

```{r prac}
prac <-
    data.frame(
        CRN = c("`PSY 609`",
                "`PSY 609`"),
        Title = c("_Prac: Violence Prevention I_",
                  "_Prac: Violence Prevention II_"),
        Grade = c("P",
                  "P"),
        Hrs = c(1,
                1),
        Term = c("Fall 2013",
                 "Winter 2014"))

knitr::kable(prac, caption = "Applied Community Psychology Parctica",
      col.names = c("CRN",
                    "Title",
                    "Grade",
                    "Credit Hours",
                    "Term"),
      align = c('c', 'l', 'c', 'c', 'l'))
```

```{r, minr}
minr <-
    data.frame(
        CRN = c("`SOC 610`",
                "`SOC 610`",
                "`PSY 510`",
                "`SOC 610`",
                "`PSY 597`",
                "`PSY 510`",
                "_`PSY 610`_"),
        Title = c("_Focus Groups_",
                  "_Qualitative Data Analysis_",
                  "_HLM/Mixed Effects Models for Longitudinal Data Analysis_",
                  "_Mixed Methods Research_",
                  "_Applied Survey Research",
                  "Categorical Data Analysis",
                  "_Structural Equation Modeling_"),
        Grade = c("A",
                  "A",
                  "A",
                  "A",
                  "A-",
                  "A",
                  "_IP_"),
        Hrs = rep(4, 7),
        Term = c("Spring 2014",
                 "Fall 2014",
                 "Winter 2015",
                 "Winter 2015",
                 "Spring 2015",
                 "Fall 2016",
                 "Winter 2017"))

knitr::kable(minr, caption = "**Minor Area Coursework**: Mixed Methods Research",
      col.names = c("CRN",
                    "Title",
                    "Grade",
                    "Credit Hours",
                    "Term"),
      align = c('c', 'l', 'c', 'c', 'l'))
```

```{r reqr}
reqr <-
    data.frame(
        CRN = c("`PSY 621`",
                "`PSY 618`",
                "`PSY 622`",
                "`PSY 624`"),
        Title = c("_Univariate Quantitative Methods_",
                  "_Ethics \\& Professional Issues in Applied Research and Practice_",
                  "_Multiple Regression \\& Multivariate Quantitative Methods_",
                  "_Research Design in Applied Psychology_"),
        Grade = c("A-",
                  "A",
                  "B+",
                  "A"),
        Hrs = c(5, 4, 5, 4),
        Term = c("Fall 2013",
                 "Winter 2014",
                 "Winter 2014",
                 "Spring 2014"))

knitr::kable(reqr, caption = "Research Methods \\& Statistics Coursework Required by Program",
      col.names = c("CRN",
                    "Title",
                    "Grade",
                    "Credit Hours",
                    "Term"),
      align = c('c', 'l', 'c', 'c', 'l'))
```

