---
title: "Integrating Theory, Methods, & Social Justice"
author: "Rachel M. Smith"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---


# I. Background & Significance

Community psychological theory values the notion that the communities in which research is taking place and/or affecting (whether directly or indirectly) should be as involved as possible in all phases of the research process, rather than solely as anonymous data points in the analysis. Community psychology thus favors inclusion over exclusion, participant voices equally with researchers' voices, and participatory and/or purposive sampling methods over convenience sampling methods. The reviewed literature will be evaluated and critiqued according to these types of community psychological standards regarding (1) _research methodologies_, (2) _data analytic approaches_, (3) _interpretations of findings_, and (4) _research dissemination._

## Rationale

This review is based in an action-oriented research framework characterized by the following core components: (1) a focus on developing and implementing innovative and inclusive research methodologies, data analytic approaches, and dissemination strategies; and (2) a diligent focus on the importance of critical reflexivity throughout the research process. The action-oriented and values-transparent community psychological research approach was born out of a resistance to research methodologies, social policies, and implementation practices that ultimately served to reinforce and/or strengthen social and economic inequalities. This foundation necessitates vigilance in critical reflexivity throughout and beyond the research process. The critical literature review provided here is intended to serve this key characteristic of community psychology.

## Research Questions (RQs)

**RQ-1:** To what extent are community psychological theories and methodologies implemented, or not, in community psychology-based research related to intimate partner violence (IPV)?

**RQ-2:** How has the implementation of community psychological research has evolved over time since the origination of the field, as well as potential trajectories based on the current state of discourse within Community Psychology and closely related research and practice disciplines?

# II. Theoretical Grounding

In a sense, the present review's theoretical grounding is best summarized in terms of the of the _Community Psychology Practice Council's_ [_"Theory into Action Bulletin"_](http://www.scra27.org/what-we-do/practice/practice-council-initatives/theory-action-bulletin/)^[[Society for Community Research and Action (SCRA)](http://www.scra27.org/)]. That is, this review is grounded in theories related to action-oriented research and their applications [@chandler2003transforming; @brydon-miller2003why; @friedman-nimz2006blending; @kelly2004community; @noffke1997professional; @prilleltensky2001value-based; @prilleltensky1997values; @seidman2012emerging], as well as social and community psychological theories related to female same-sex intimate partner violence. The underlying purpose of this systematic review is to examine the intersections that exist across these theoretical, methodological, and problem-specific domains in terms of their actual applications and manifestations in various settings. Below is a list of theoretical and conceptual frameworks specifically guiding the proposed review.

`r tufte::newthought("Theory Specific to Community Psychology (CP):")`

- _The Action Research Cycle & Community-Based Participatory Action Research_ [CBPR; @fine2004participatory; @chandler2003transforming; @brydon-miller2003why; @friedman-nimz2006blending; @kelly2004community; @noffke1997professional; @prilleltensky2001value-based; @prilleltensky1997values; @seidman2012emerging; @anders1966action]
- _Ecological systems theory and the Social Ecological Model_ [@stokols1996translating; @visser2007social; @walker2006handful; @centers2015social; @kloos2009social; @anderies2004framework; @baral2013modified; @stokols1996translating]
- _Community Empowerment & Individual Empowerment_ [@speer1995community; @riger1993what; @beeker1998community; @cobb1993empowerment; @collins2002black]
- _[Community] Health Promotion_ [@stokols1996translating]

`r tufte::newthought("Theory Related to both Community Psychology and IPV Intervention and Prevention:")`

- _Coordinated Community Response_ [CCR; @gondolf2007theoretical; @barner2011interventions; @dutton2007duluth]
- _Minority Stress Theory & Resilience_ [MS; @meyer2003prejudice; @meyer2010right; @meyer1995minority; @meyer2015resilience]
- _Risk Factors vs. Protective Factors_ [@baral2013modified; @whitaker2014linking; @tharp2013systematic; @walton-moss2005risk; @heckert2004battered]

`r tufte::newthought("Intersecting Community Psychology Theory \\& Research Methodology")`

- _Grounded Theory Methods_ [@charmaz2006constructing; @corbin1990basics; @strauss1994grounded]
- _Mixed-Methods Research_ [@morgan2014mmr; @creswell2013research; @greene1989toward; @johnson2007toward]
- _Program Evaluation_ [@greene1989toward; @kidder1987qualitative; @mertens2012program; @owen1999program; @royse2009program]

# III. Systematic Literature Review Methodology

```{r setup, echo=FALSE, results='hide', message=FALSE, warning=FALSE, cache=FALSE, fig.show='none', fig.keep='none'}
source("bibs.R")
knitr::opts_chunk$set(echo=FALSE)
```

The purpose of this review is to provide a critical methodological overview of the available empirical research related to intimate partner violence (IPV) intervention and prevention efforts through a community psychological lens. As such, this review is specifically focused on the _applied_ methodologies employed within community-based and action-oriented research frameworks. This overarching purpose stems primarily from the goal of informing IPV intervention and prevention approaches specific to same-gender IPV perpetration among female-identified individuals. However, while there is currently a burgeoning body of research related to the causes, correlates, and consequences of IPV within the context of women's same-gender relationships, the below-described literature searches indicated that there is no currently available empirical evaluation research examining interventions implemented to address IPV within such contexts.

## Literature search strategy

<!-- _B. Focal data bases_ -->

Six separate literature searches were conducted using the [_PsycINFO_](http://www.apa.org/pubs/databases/psycinfo/) and [_Web of Science_](http://wokinfo.com) online citation indexing databases via the [Portland State University library website](library.pdx.edu):

<!-- _C. Key search terms_ -->

1. _Intimate Partner Violence, Domestic Violence, or Partner Abuse - General_
2. _Intimate Partner Violence, Domestic Violence, or Partner Abuse Interventions_
3. _Intimate Partner Violence, Domestic Violence, or Partner Abuse Intervention Evaluations_
4. _Female Same-Sex/Same-Gender Domestic Violence, or Partner Abuse - General_
5. _Female Same-Sex/Same-Gender Domestic Violence, or Partner Abuse Interventions_
6. _Female Same-Sex/Same-Gender Domestic Violence, or Partner Abuse Intervention Evaluations_

<!-- D. Inclusion/exclusion criteria -->

Because this review is not intended to provide a cross-national examination of IPV interventions research, each of the above literature searches was restricted to empirical studies conducted within the United States. In addition, to focus the review around a community psychological framework and intimate partner violence, results were initially confined to articles published in scholarly peer-reviewed journals specific to Community Psychology. The list Community Psychology journals included _The American Journal of Community Psychology_ and the additional publications, provided in Table `[`  `]`,<!--map.cp--> endorsed by the Society for Community Research and Action (SCRA) as related to Community Psychology [@scra2017other]. This restriction yielded a limited number of empirical articles specific to intimate partner violence interventions (see Table `[`  `]`). Thus, the literature searches were revised to also include articles published in any of the following violence-specific publications: _Journal of Interpersonal Violence_, _Journal of Family Violence_, _Violence Against Women_, or _Violence and Victims_.<!--^[_"Journal of Interpersonal Violence (JIV), published 20 times a year, is devoted to the study and treatment of victims and perpetrators of interpersonal violence, addressing the causes, effects, treatment, and prevention of all types of violence"_ [@jiv].]--> These additional publications were included based on results from a database search of IPV-related terms conducted with no constraints imposed on the publishing journal, which revealed that these journal publish the majority of IPV-related research ($n_{articles} =$ `r pander(as.character(jv.n[, 1]))`, respectively), and (2) the alignment of the topical and methodological foci of these violence-related journals with community psychological principles and values. Finally, each database search was restricted to empirical studies published between 1965 and 2017 [i.e., the year of the [Swampscott conference](http://www.scra27.org/publications/tcp/tcp-past-issues/tcpsummer2014/remembering-swampscott/) and the present year; @fryer2008some].

Details regarding the number of results obtained from each of the above-listed database searches are provided in Table []. Collectively, the literature database searches yielded `r n.init` journal articles, of which `r n.inits3` focused on intimate partner violence prevention and intervention programs, approaches, and evaluations, ; whereas the remaining `r n.inits4` consisted of research specific or closely related to IPV among sexual minority women and LGBTQ populations in general, but not necessarily specific to IPV prevention nor intervention among these populations. The majority of the latter research sub-category's initial results focused primarily on the prevalence of IPV among sexual minority populations, as well as causal antecedents, risk factors, correlates, and consequences of IPV among members of these target sub-populations.

Through a systematic evaluation of the full set of results obtained from the database searches, described in a later section, a large number of the latter category's articles published in the included violence-specific journals were determined to be, at best, loosely relevant to the overall community-psychological focus of this review. As such, results from this LGBTQ-IPV research sub-category were restricted to studies published within any of the community-psychology-related scholarly journals in an effort to maintain the overall community-psychological focus of this review [see Table `[`  `]`; @scra2017other]. The final set of `r nrow(MAP)` articles included in this review therefore consists of `r nrow(MAP[MAP$scat == "S3", ])` empirical studies related to IPV intervention and prevention program evaluations in general, and `r nrow(MAP[MAP$scat == "S4", ])` studies specific to sexual minority populations.


<!-- This review of the empirical literature described above is structured ... TODO ... -->

As previously noted, the research reviewed here is conducted within a Community Psychological or closely related research framework and thus represents a subset of the available IPV-related empirical literature.

The selection of empirical literature, representing a community-psychology-focused subset of the U.S.-based IPV-related literature, was reviewed using a `primarily deductive` _qualitative comparative analytic approach_ [_QCA_; @leech2007array; @onwuegbuzie2017framework]. This review approach was conducted in two phases, the first of which served as the initial data reduction, organization, and quality-control process undertaken to determine the final set of articles to be included in the formal review. In the first QCA procedure, each article in the initial full set of results from the previously-described literature database searches ($N = )

The second QCA phase served as a systematic method for examining the similarities, differences, and anomalies among the final set of reviewed articles according to the above-described two categories determined in the first QCA phase data reduction and organization process [@onwuegbuzie2017framework; @onwuegbuzie2009qualitative]. That is, the reviewed literature was categorized according to the commonalities in overarching research topics, target populations, sampling frames, sampling and data collection methodologies and measures, data analytic approaches and procedures, findings, and implications.

The qualitative comparative analysis of the reviewed literature was aided by the _`RQDA`_ package created for use with the _`R` Statistical Programming Language and Environment_ [@R-RQDA; @R-base].


# IV. Methodological Considerations

## Defining Methodological Rigor

The notion of "scientific rigor" is particularly important in evaluating a set of applied social science research studies employing varying methodologies. This is because "rigor" is not necessarily clearly defined across methodologies, and some research philosophies do not consider certain methodologies as capable of achieving scientific rigor at all.

For the purposes of this review, methodological rigor is broadly defined as the extent to which a given study employs research methods that best address the overarching research question(s) and/or hypothesis/hypotheses, and the quality of the implementation of those methods. This definition of methodological rigor therefore does not prioritize a particular method nor category of methods (e.g., quantitative over qualitative, mixed-methods over single-methods, etc.), but rather prioritizes the choice and implementation of methods employed to address a given study's purposes. In addition, this definition of methodological rigor allows for more specific and in-depth consideration of the limitations presented, and not presented, in each study's report.

# V. Integrative Literature Description and Review

## Publication Years

Although the previously-described database searches allowed for any research published between 1965 and the current year (2017), the earliest publication date in the literature reviewed here is `r min(MAP$year)`. This timespan aligns with the political and legislative history of U.S. domestic violence policy and social movement(s). For instance, the original Violence Against Women Act, which imposed provisions to actually enforce the illegality of family violence perpetration, was passed in 1996 [@legates2001their, Ch. 3].


## Specific Research Topics

The primary research topic across the empirical literature reviewed here is evaluation of interventions targeting IPV perpetration or victimization. However, the level, scope, and specific focus on evaluations is somewhat varied across this literature.


<!-- # V.1. IPV Interventions Research -->

# Review of Key Findings

## <!--Secondary and Tertiary -->IPV Perpetrator Intervention<!-- and Prevention--> Program Evaluations <!-- EDIT HEADING TITLE (MAKE SHORTER) -->

`r tufte::newthought("Brief History of U.S. IPV Perpetrator Interventions.")` Efforts to address violence against women and in particular intimate partner and sexual violence in the United States began with an overall focus on treatment and tertiary intervention approaches, which, understandably, were primarily focused on addressing the immediate needs of victims.<!-- CITE -->  Until IPV perpetration became a crime in all 50 states, these efforts were in large part initiated and sustained on "grassroots" levels, connecting with and building upon one another toward efforts to affect more large-scale changes at the policy and structural levels. The criminalization of IPV perpetration was eventually followed by the enactment and enforcement of mandatory arrest laws across the country, which, while varied in scope and levels of implementation, essentially require police officers responding to calls deemed characteristic of domestic violence impose some level of punitive action against the accused offender in the situation. These laws were created and continue to be enforced under the goal of ensuring victims' safety. The U.S. Violence Against Women Act of 1996 shared a similarly victim-safety-centered purpose and, among a plethora of policy implications, was the first national-level policy providing at least a minimal amount of federal and state-level funding allocations specifically for developing and sustaining services for victims of IPV in each U.S. state.


## Early Evaluations of IPV Perpetrator Intervention Programs<!-- (late 1990s to early 2000s) --><!-- EDIT HEADING TITLE -->

Using naturalistic observations<!-- of program practices --> and key informant<!--(i.e., program participants' current romantic partners)--> reports of IPV perpetrators' reassault rates `during the first`<!-- over the course of--> 15 months following their initial intake into the `intervention program`, @gondolf1999comparison provides a<!--`foundational`--> comparative evaluation of four IPV perpetrator intervention systems in four U.S. cities (i.e., Pittsburg, PA; Houston, TX; Dallas, TX; and Denver, CO).<!-- EDIT: TOO LONG OF A SENTENCE--> Findings from this study are, however, somewhat mixed in that comparisons to evaluate differences in reassault rates across the four study sites, representing a continuum of least-to-most comprehensive IPV perpetration intervention systems, showed few meaningful differences across intervention sites.\ `Distinctions across the four sites are, however, more evident when individual perpetrator characteristics (e.g., psychopathology, substance abuse, previous arrests, etc.) and referral sources (e.g., court-mandated versus referral sources outside the court system) are also taken into account`. Further, while there was no significant effect of intervention site on reassault rates, the effect of the most comprehensive intervention system among the four included in the study `does tend toward significance`, particularly when this site's effect is compared with the least comprehensive intervention system included in this evaluation.

Overall, the total recidivism rate observed across all four programs evaluated in @gondolf1999comparison\'s investigation ($n_{total} = 656$) was 32% <!-- (_n_ = 210) --> for physical abuse and 43-70% for non-physical abuse (i.e., controlling behaviors, 45%; verbal abuse, 70%; and threats, 43%). In addition, 72% <!-- (_n_ = 343) --> partner respondents reported that they "feel 'very safe'" and 66% <!-- (_n_ = 281) --> indicated that they were "'very unlikely' to be hit". However, only 12% <!-- (_n_ = 54) --> rated their overall quality of life following their partners' completion of the intervention as "better", another 12% rated their quality of life as "worse", while 22% <!-- (_n_ = 100) --> rated their quality of life as the "same" as it was prior to their partners' intervention participation (p. 53).

Despite these mixed findings, @gondolf1999comparison\'s, relatively, early investigation into the possible differential effects of IPV perpetrator intervention systems representing four distinct points along a continuum from least-to-most comprehensive systems informs questions regarding system-, dyadic-, and individual-level factors that may influence these systems' efficacy at reducing reassault among men who have perpetrated IPV toward one or more female intimate partners. In particular, @gondolf1999comparison\'s findings regarding differences across the four intervention systems were most informative to understanding the effectiveness of IPV perpetrator programs when multiple levels of analysis are considered. That is, the effects of intervention systems' characteristics (i.e., comprehensiveness of services and intervention program length) on reassault rates appears `rather` sensitive to the inclusion of system-level variables not specific to the IPV perpetrator intervention itself (e.g., referral sources) and dyadic- and individual-level variables (e.g., victim-perpetrator contact during the 15-month study period, perpetrators' IPV-related and non-IPV-related criminal backgrounds, perpetrators' substance use or abuse, etc.) in each analysis.

The primary data source for @gondolf1999comparison\'s study's outcome variables is key informant reports provided by participating IPV perpetrators' current romantic partners, `regardless of whether those partners were` the original victims leading to the men's intervention program participation<!-- EDIT -->. This sampling and data collection method is an interesting approach to evaluating IPV perpetrator interventions, and the use of key informant reports (e.g., victims', current and/or past romantic partners', and intervention program facilitators' perspectives used as primary or secondary reports of program participants' behavior) is `somewhat thematic across a subset of subsequently-published literature included in this review`<!-- EDIT --> [e.g., @gregory2002effects; @silvergleid2006batterer]. `An additionally notable characteristic of` @gondolf1999comparison\'s `evaluation report` is the transparency with which the study's results are presented. While the evaluation ultimately provided, at best, mixed support for more the effect of more comprehensive IPV perpetration intervention systems, the results are presented such a way that acknowledge the state of this specific practice's field, which, at the time of the study's publication, is possibly best characterized as disjointed and in need of a more concrete and consistent evidence-base.

`In a separate effort to` inform the question of IPV perpetrator intervention effectiveness from the victims'/survivors' perspectives, @gregory2002effects conducted in-depth one-on-one interviews with 33 women identified via police reports as having experienced IPV victimization perpetrated by men referred to a local IPV perpetrator intervention program in a rural Ohio county. Interview questions sought information regarding the offenders' behaviors before, during, and after their participation in the intervention. Regarding survivors' accounts of offenders' behaviors prior to being referred to the intervention, the authors found that many of the men entering the intervention had also been physically violent with past romantic partners, close relatives, and male friends. In addition, a substantial proportion of survivor respondents indicated that jealousy, substance abuse, and family-related issues (e.g., issues related to children, finances, household chores, etc.) were apparent causes of conflict leading to the perpetrators' use of violence. Survivors' also provided insights into their assessments of more underlying causes of abuse, including issues related to power and control, their partners' low self-esteem, and conflict related to sexual/intimacy issues and the perpetrators' infidelity in the relationship. Regarding program participants' partners' accounts of the intervention's effectiveness, the majority of the 33 respondents in @gregory2002effects\'s evaluation indicated either a decrease or complete elimination of violence in their relationships, while a third of the partners reported that the intervention program in fact became a new source of conflict in their relationship, and 19% reported abuse during or following the offenders' program completion.

A particularly notable descriptive finding from @gregory2002effects\'s investigation is that, on average, over seven years lapsed between the first occurrence of IPV in the relationships accounted for by the study's survivor respondents and the IPV incident resulting in the perpetrators' referrals to the intervention program. Although not explicitly connected in the study's findings report nor discussion, this finding may inform survivor respondents' apparent consensus that jail time should be an immediate and/or unconditional sanction imposed against individuals found guilty and/or under investigation for IPV perpetration. Further, an average time-lapse of this magnitude indicates a potentially critical flaw in the implantation of any form of a coordinated community response to IPV [@hart1995coordinated].

@gregory2002effects\'s evaluation is restricted to female survivors' accounts of male IPV perpetrators court-mandated, either as part of post-sentencing probationary requirements or deferred-sentencing conditions, to complete the intervention, and therefore does not include accounts of the intervention programs' participants who are not referred to the program by the courts. @gregory2002effects\'s sample further excludes accounts of same-gender IPV perpetration or victimization, as well as IPV perpetrated by female-identified individuals toward male-identified partners. This sampling frame is similar to that defined in @gondolf1999comparison\'s investigation (summarized above) both in terms of the specific included and excluded populations, as well as the fact that the sampling restrictions in both studies are, at least to some degree, a function of the populations served by the study sites themselves. That is, at the time the studies were conducted, the intervention programs evaluated in both investigations provided IPV perpetrator intervention services only to male-identified individuals who perpetrated IPV toward female-identified partners.

@hendricks2006recidivism conducted a comparative evaluation of two IPV perpetrator intervention programs in a small metropolitan Wisconsin county [@ingram2012nchs]. Although @hendricks2006recidivism ultimately describes the programs evaluated their investigation as two independent interventions, one of the programs, _"Reasoning & Rehabilitation (R&R)"_ is in fact evaluated as a `sort of nested or secondary` intervention within the county's larger IPV perpetrator intervention system, _"Stopping Abuse for Everyone (SAFE)"_ (p. 704). That is, individuals are referred to the _R&R_ program `if they are determined as in need of` greater levels of supervision based on a clinical assessment administered during the _SAFE_ program's intake process. Such individuals are expected to return to and complete the _SAFE_ program's intervention after completing the additional _R&R_ program. @hendricks2006recidivism\'s investigation also included an evaluation of the predictive validity of the _Level of Service Inventory–Revised_ [_LSI-R_; @andrews1994level], which is the assessment administered to determine intervention participants' levels of risk and need at intake for the _SAFE_ program. Regarding the latter, results from logistic regression analyses provided minimal support for the LSI-R scale's accuracy, sensitivity, and specificity in correctly classifying recidivating intervention participants (overall classification accuracy = 66% correct). However, while formal logistic regression analysis was not similarly conducted to examine the measure's predictive accuracy regarding program placement, comparisons<!-- via between-subjects factorial--> via cross-tabulations and chi-square ($\chisq$) analyses revealed significant differences in both LSI-R scores and recidivism rates among intervention participants. Specifically, participants who completed the _SAFE_ program without referral to the _R&R_ program (14.4% recidivated) had significantly lower recidivism rates than those who completed both interventions (32.4% recidivated; $\chisq(1) = 6.26,~p < .05$). As @hendricks2006recidivism note, because participants were referred to the _R&R_ program on the basis of their LSI-R scores, these differences in recidivism rates do not necessarily inform comparisons regarding each intervention program's individual effectiveness at reducing or preventing future violence perpetration among participants. However, a possibly missing point in @hendricks2006recidivism\'s report and analytic conclusions is that these observed differences may provide support for the discriminant validity of the LSI-R as a measure effective in determining the relative risk and needs levels of IPV perpetration intervention participants.

In general, research on the effectiveness of IPV perpetrator intervention programs in the late 1990s and early 2000s, including the above-reviewed research, provides a mixture of evidence in favor and not in favor of these programs' effectiveness [@feder2005meta]. The above-reviewed subset of the IPV-related literature reiterates the general ambiguity regarding effective approaches to IPV interventions. Nonetheless, it is important to understand the processes underlying successful outcomes (e.g., reduced or eliminated recidivism among participants) in these interventions. @silvergleid2006batterer provide one such exploration of the key processes facilitating positive change among men who successfully completed an IPV perpetrator intervention program in Portland, Oregon.

@silvergleid2006batterer conducted in-depth, semi-structured, one-on-one interviews with ten intervention group facilitators and nine men who were within two-weeks of having completed their participation in the intervention and who were nominated by group facilitators. Four levels of change processes were identified through inductive thematic analysis of the interview data: (1) "community and extratherapeutic influences", (2) "organizational influences", (3) "group processes", and (4) "individual psychological development" (p. 144). The group-level processes seem especially influential in terms of facilitating a _process_ of change, in that this level of influence is further categorized into three sub-processes that appear to build from one another: (1) balancing support and confrontation, (2) sharing and hearing stories, and (3) modeling and mentoring. Facilitators' accounts further emphasized the group-level influences as instrumental in the process underlying intervention participants' "'resocialization' into a new manhood" (p. 151).

@contrino2007compliance quantitatively examined intervention program participants' levels of compliance with program requirements (e.g., attendance, engagement with the program, maintaining sobriety, nonviolence, etc.) and the extent to which participants retain key components of the intervention's content (e.g., power and control dynamics versus non-controlling behaviors). This investigation's focus aligns with @silvergleid2006batterer\'s qualitative findings regarding key influences underlying and facilitating IPV perpetrator intervention program participants' change processes. Specifically,<!--both program participant and facilitator --> interviewees in @silvergleid2006batterer\'s sample emphasized the importance of learning new skills (e.g., taking a 'time-out') and engagement with program activities (e.g., reading required texts, journaling, acknowledging their past violent behaviors and the impact of those behaviors on others, etc.) in the change processes experienced by program participants:

> "The most emphasized aspect of awareness was the participant’s new understanding of the effects of their abuse on others. For many men, truly sit- ting with that understanding, the devastating impact of their actions on those around them, was a strong impetus for change" (@silvergleid2006batterer, p. 153).

Findings from @contrino2007compliance\'s process evaluation somewhat reiterate @silvergleid2006batterer\'s findings in that participants' recall of intervention content related to power and control dynamics  levels of compliance with certain domains of program expectations, including (1) using techniques to avoid violence, (2) process-consciousness and communication skills, (3) self-disclosure of ones's feelings and non-defensiveness, and (4) use of respectful language. Other assessed program expectations including participants' program attendance, active engagement in group sessions, sobriety, nonviolence, and help-seeking were not associated with the number of forms of power and control they were able to recall [see @gondolf2009clinician].

# VI. Critical Methodological Evaluation

Research conducted within the subset of community psychology focused around intimate partner violence was initially evaluated according to the level of inclusion and exclusion of the historically marginalized population of interest: sexual minority women (SMW). The implementation of action-oriented Community Psychology methodologies and analytic approaches will then be reviewed within each of these categories (i.e., inclusion or exclusion of SMW) in terms of (1) the appropriateness of the methods to the research question, (2) how the methods facilitated the inclusion or exclusion of sexual minority women, and (3) whether and how (where applicable) exclusion of sexual minority women is justified.

## Overarching Critique Criterion

`r tufte::newthought("Rigor in Action-Research Methods")`:

- Choice, description, justification, appropriateness, and execution of overarching methodology (i.e., quantitative, qualitative, or Mixed-Methods), sampling frame definition, sampling and data collection methods, and analytic approaches.
- Interpretations of results, limitations, results interpretations.
- Presentation, dissemination, application, and accessibility of the research.
- Transparency and reproducibility of the research methods, findings, and limitations

`r tufte::newthought("Stakeholder Input.")`:

- Are efforts made to ensure that _all available_ stakeholders' and informants' voices and accessibility considered equally, and that certain voices are not unjustifiably privileged over others?
- Are primary and distal stakeholders and informants to the research given access to reports of a given project's progress and/or findings? Is such access in fact accessible (i.e., free and easy to locate)?

`r tufte::newthought("Interpretations of Findings.")`

- Is feedback from key stakeholders and informants to the research accepted and genuinely considered by the core research team?
- Are efforts made to ensure that _all available_ stakeholders' and informants' voices and accessibility considered equally, and that certain voices are not unjustifiably privileged over others?

`r tufte::newthought("How the methods facilitate the inclusion or exclusion of specific populations")`

- Whether and how exclusion of specific populations is justified (if applicable)

`r tufte::newthought("How the methods facilitate the inclusion or exclusion of _sexual minority women_")`

- Whether and how exclusion of _sexual minority women_ is justified (if applicable).



## Methodologies & Methods Utilized

The majority of the reviewed studies follow quantitatively-based methodologies ($n = 14;~~61\%$), with just over a quarter ($n = 6$) employing qualitatively-based methodologies, and only four studies utilizing mixed-methodological approaches. Of the reviewed quantitatively-based studies, $86\%$ ($n = 12$) employed experimental and/or longitudinal, rather than cross-sectional, designs. All but one of the quantitative studies ($93\%$) used self-report survey measures as the primary datasource. Four of the six qualitatively-based studies used group interviews as the primary data collection method, one administered and analyzed responses to a qualitative self-report survey, and one employed a multi-method qualitative approach. The methods represented among studies following mixed-methodological designs include experimental and longitudinal mixed-methods, focus groups, and qualitative and quantitative self-report measures.

## Populations Included/Sampling Frames

## `Explicitly` Excluded Populations

## _A. Strengths_

## _B. Limitations_

# Conclusions

# References
