---
title: "Community Methods Minor Comprehensive Examination"
author: "Rachel M. Smith"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---

\newpage

# \textsc{\LARGE{(1.a.) Definition of the method}}

\Frule

# Mixed-Methods Research


> [One approach to mixed-methods research developed by @morgan1998practical and referred to here as the "**complimentary sequence**" approach, involves\] "... _combining_ qualitative and quantitative methods ..." [@morgan1998practical, p. 362, _emph. added_].

> "The core of [the **complimentary sequence**] approach is an effort to _integrate_ the complimentary strengths of different methods through a division of labor" [@morgan1998practical, p. 366, _emph. added_].

> > "This amounts to _using a qualitative and a quantitative method for different but well-coordinated purposes_ within the same overall research project" [@morgan1998practical, p. 366, _emph. added_].

> > "The division of labor is accomplished through _two basic decisions_ ..." [@morgan1998practical, p. 366, _emph. added_].

> > > [1\] "... a _priority_ decision that pairs a principal method with a complimentary method and ..." [@morgan1998practical, p. 366, _emph. added_].

> > > [2\] "... a _sequence_ decision that determines whether the complementary method precedes or follows the principal method" [@morgan1998practical, p. 366, _emph. added_].

> [_**Equal-status mixed-methods research designs**_ are those\] "... where _high quality_ qualitative and quantitative data are collected ... " [and] "... the qualitative and quantitative research paradigms are given equal weight" [@stefurak2016mixed, p. 347].

> > "Sometimes it is said that paradigms are incommensurable and cannot be mixed. _However, they can be, using a **dialectical and dialogic logic**. That is why **equal-status mixed methods designs** are also called **interactive mixed methods designs**_" [@stefurak2016mixed, p. 347, _emph. added_]


`r tufte::newthought("\\Large{Mixed-methods research, in general, is:}")`

\vspace*{1em}

\LARGE{``}

> > ... a research approach or methodology:

> > - focusing on research questions that call for real-life contextual understandings, multi-level perspectives, and cultural influences;

> > - employing rigourous quantitative research assessing magnitude and frequency of constructs and rigorous qualitative research exploring the meaning and understanding of constructs;

> > - utilizing multiple methods (e.g., intervention trials and in-depth interviews);

> > - _intentionally integrating or combining these methods to draw on the strengths of each_;

> > - framing the investigation within philosophical and theoretical positions

\vspace*{-1em}

> > `r tufte::quote_footer("\\LARGE{''}")`

> > `r tufte::quote_footer("@creswell2016best, (p. 4, _emph. added_)")`


-----

Mixed-methods research provides a framework for approaching a given research question or hypothesis through multiple data collection methodologies, data structures, or data analytic methods in ways that capitalize, for lack of a better term, on the relative strengths, weaknesses, and appropriateness of a one versus the other. In general, data are collected and analyzed in one of two types: qualitative or quantitative. However, variations certainly exist within this dichotomized typology such that qualitative data can often evolve or be manipulated into representing discrete categories that can, sometimes, be conceived of and analyzed as continuous, and therefore quantitatively-based, data. Conversely, quantitative data can be used to compute distance matrices in order to form clusters among a set of cases, and those clusters can then be examined in more qualitative frameworks that inform the qualitative distinctions across different groups. These brief example scenarios reflect the notion that the very structure and nature of the data collected in a given research project can be considered on a continuum of quantitative-to-qualitative (or vise-versa) 


\SFrule

# Qualitative Research Methods


> "Qualitative approaches to research reflect an underlying philosophy of science and set of methods that embody many of the values of community research and action (Banyard & Miller, 1998)" [@stein2004asking, p. 21].

> "Some community scholars advocate qualitative approaches as a way to better understand individual diversity and the nuance of social context" [@stein2004asking, p. 21].

> "By emphasizing detailed, first-hand descriptions of people and settings, qualitative approaches methods are thought to enhance the study of behavior embedded in a larger social world (Trickett, 1996)" [@stein2004asking, p. 21].

> "Qualitative methods are also used to arrive at more ecologically-sensitive constructs upon which quantitative measures can be based" [@stein2004asking, p. 21].

> "Qualitative findings are said to help dispel misconceptions about marginalized populations perpetuated by the use of quantitative measures originally developed with mainstream samples (Dumka [et al.], 1998; Maton [et al.], 1998)" [@stein2004asking, p. 21].

> [Qualitative research is comprised of a set of tools designed, in large part, to\] "... facilitate researchers' knowledge about the experiences and perspectives of the group under study, as well as the development of research instruments that are useful and relevant" [@hughes2002using, p. 776].

> "**Focus groups** are in-depth group interviews employing relatively homogenous groups to provide information around topics specified by researchers" [@hughes2002using, p. 776, _emph. added_].

> [Focus groups\] "... have several strengths that make them particularly useful for facilitating research that reflects the social realities of a cultural group" [@hughes2002using, p. 776].

> "Focus groups provide researchers with _direct access_ to the language and concepts participants use to _structure their experiences_ and to think and talk about a designated topic" [@hughes2002using, p. 776, _emph. added_].

> "Within-group homogeneity prompts focus group participants to elaborate stories and themes that help researchers understand how participants structure and organize their social world" [@hughes2002using, p. 776].

> "In their reliance on social interaction, focus groups can also help researchers identify cultural knowledge that is shared among group members as well as to appreciate the range of different experiences individuals within a group may have" [@hughes2002using, p. 776].

> [Qualitative methods bring\] "... researchers closer to a _phenomenological understanding_ of a cultural group. Such an understanding can help investigators ask better research questions and develop the measures needed to study them" [@hughes2002using, p. 776, _emph. added_].

-----


Community-based research is inherently tied to qualitative research methods by virtue of a commitment to evaluating and addressing social phenomena through perspectives and research approaches that elevate the nuanced variability that exists within the larger ecology of a given target phenomenon.

\SFrule

# Quantitative Research Methods


> [Quantitative methods\] "... facilitate rigorous hypotheses testing, produce research that is both internally valid and externally generalizable, and assess cause-and-effect relationships between constructs" [@connell2016introduction, p. 121].

> "... the quantitative methods used by community-based researchers provide a strong framework for investigating complex and contextualized phenomena in their own right" [@connell2016introduction, p. 121].

> "To maintain pace with the field's complex theories of the 'interplay between people and contexts' [@shinn2000cross, p. 185], community researchers should use data-analytic methods that best represent the relationship of ecological and contextual domains to the phenomena being investigated. This means that community researchers need to adopt measurement approaches that do a better job of capturing contextual information, such as social network analysis (SNA) or geographic information systems (GIS) methods [@luke2005getting], or 'ecometric' approaches (Raudenbush & Sampson, 1999, p. 3)" [@connell2016introduction, pp. 121--122].

> > "Community researchers also must make greater use of data-analytic methods that incorporate contextual (i.e., setting-level) and cross-level (i.e., interactions between setting-level and individual-level) effects ..., as well as more complex processes (e.g., indirect or mediating effects, moderation effects) cross-sectionally, longitudinally, and across contextual settings ..." [@connell2016introduction, p. 122].

> > "... analytic methods should be dynamic and adaptable to the challenges of complex research designs and data structures" [@connell2016introduction, p. 122].

> > > "... previous examinations of the state of the field's statistical methods [e.g., @luke2005getting] revealed that community researchers continue to rely on more traditional data-analytic methods (e.g., analysis of variance [ANOVA], regression, and correlation), rather than methods permitting greater complexity (e.g., structural equation modeling [SEM], cluster analysis, and SNA) or contextualization (e.g., multilevel modeling [MLM] and GIS analysis)" [@connell2016introduction, p. 122].


-----


Quantitative methods in community psychology are intended to produce not only reliable and generalizable insights regarding the constructs of interest for a given community-based research endeavor, but also to provide such generalizability and reliability through an ecological lens that accounts for or incorporates, via both the data collection _and_ data analytic methods, contextual understandings of the phenomena of interest.

\newpage

# \textsc{\LARGE{(1.b.) Discuss an application of the method}}



# Quantitative Methods



\
