---
title: "Community Methods Minor Comprehensive Examination"
author: "Rachel M. Smith"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---

\newpage

# \centerline{\textsc{\huge{(1.a.) Definition of the method}}}

\Frule

# Community-Based Participatory Research & Participatory Action Research


> "Participatory action research represents a stance within qualitative research methods --- an epistemology that assumes knowledge is rooted in social relations and most powerful when produced collaboratively through action"  [@fine2003participatory, p. 173].

> > "PAR ... has typically been practiced within community-based social action projects with a commitment to understanding, documenting, or evaluating the impact that social programs, social problems, or social movements bear on individuals and communities"  [@fine2003participatory, p. 173].

> > "... at its core [PAR] articulates a recognition that knowledge is produced in collaboration and in action" [@fine2003participatory, p. 173].

> "[PAR] has been gradually gaining recognition in the social sciences promising strategy for actively involving research participants in the development and implementation of the research process while attempting to pursue socially relevant research issues" [@balcazar2004participatory, p. 17].

> "... [PAR] not only aims to empower individuals, but more important, it aims to facilitate higher order social, organizational, or political change" [@balcazar2004participatory, p. 17].

> "PAR combines social investigation, education, and social action to define and address social problems, particularly among disenfranchised and oppressed groups..." [@balcazar2004participatory, p. 17].

> "**[PAR] is both a research ideology and a strategy for conducting research**" [@balcazar2004participatory, p. 17; _emph. added_].

> > "As an ideology, PAR represents a set of beliefs regarding the role of social science research in alleviating social injustice and promoting community involvement in social change efforts" [@balcazar2004participatory, p. 17].

> "... [participatory] research was developed to change something about the specific situation right at that time, rather than, or as well as, later" [@senn2005you, p. 356].

> "Participatory research involves a very different level of involvement. A study can be said to be participatory when it requires the involvement of people from the group or community of interest in some or all stages of research" [@senn2005you, p. 360].

> > "\ @maguire1987doing suggested that 'participatory research combines three activities: investigation, education, and action' (p. 29)." [@senn2005you, p. 360].

> > "The _investigation_ part of the process is a 'social' investigation 'involving participation of oppressed and ordinary' people in problem posing and solving [@maguire1987doing, p. 29]" [@senn2005you, p. 360, _emph. in orig._].

> > "Both the participants in the study and the researchers are _educated_ in the process about the possible causes of the problem 'through collective discussion and interaction' [@maguire1987doing, p. 29]" [@senn2005you, p. 360, _emph. in orig._].

> > "... both the researchers and the participants 'join in solidarity to take collective _action_, both short and long term' [@maguire1987doing, p. 29, emphasis added]" [@senn2005you, p. 360, _emph. in orig._].

> > "The reasoning is clear. The people who are going to be affected by change efforts should be involved in directing that change, and mutual education will be necessary for that to occur" [@senn2005you, p. 360].

\SFrule

# Geographic Information Systems & Place-Based Methods

## Geographic Information Systems

> "Geographic information systems (GIS) are computer-based programs designed for the storage, visualization, analysis, and display of data that contain spatial components" [@lohmann2016geographic, p. 93].

> "The software for GIS allows for the _visual layering_ of geographic detail ... to assist in better understanding the relationships between spatial variables" [@lohmann2016geographic, p. 93, _emph. added_].

> > "The data generally take one of three forms: points ..., lines ..., and polygons. ... These categories contain some flexibility, however ..." [@lohmann2016geographic, p. 93].

> "GIS also has many analytic tools to extract information concerning the spatial variables. Among the more basic of these are the capacity to analyze the distance and area of any geographic variable" [@lohmann2016geographic, p. 93].

> > "More complex analytical operations involve _querying_ --- searching selected spacial variables for locating where specific criteria are met. ... By conducting queries for different spatial variables, areas of spacial correspondence can be located and analyzed" [@lohmann2016geographic, p. 93, _emph. added_].

## Place-Based Methods

> [An underlying assumption of place-based research is that\] "... the _development of self identity_ is not restricted to making distinctions between oneself * significant others, but _extends with no less importance to objects and things, and **the very spaces and places in which they are bound**_" [@proshansky1983place, p. 57, _emph. added_].

> [Place-based research methods\] "... consider the influence of the physical settings that are inherently part of any socialization context on self identity" [@proshansky1983place, p. 58].

> > "In a constantly changing technological society, it is imperative to ask the question, 'What are the effects of the built environment?' not only in regard to the personality development of the individual, but also in terms of how he defines himself within society" [@proshansky1983place, p. 58].

> [Place-based methods\] "... stress the importance of an ecological approach in which the person is seen as involved in _transactions_ with a changing world" [@proshansky1983place, p. 59, _emph. added].

> > "... the psychologically healthy state of a person's sense of self is not a static one, rather it is characterized by growth and change in response to a changing physical and social world" [@proshansky1983place, p. 59].

> [**Place-identity**\] "... is a sub-structure of the self-identity of the person consisting of, broadly conceived, cognitions about the physical world in which the individual lives" [@proshansky1983place, p. 59].

> > "These cognitions represent memories, ideas, feelings, attitudes, values, preferences, meanings, and conceptions of behavior and experience which relate to the variety and complexity of physical settings that define the day-to-day existence of every human being" [@proshansky1983place, p. 59].

> > "At the core of such physcial environment-related cognitions is the 'environmental past' of the person; a past consisting of places, spacing and their properties which have served instrumentally in the satisfaction of the person's biological, psychological, social, and cultural needs" [@proshansky1983place, p. 59].

\SFrule

# Program Evaluation


> [Program evaluators\] "... use social research methods to study, appraise, and help improve social programs, including the soundness of the programs' diagnoses of the social problems they address, the way the programs are conceptualized and implemented, the outcomes they achieve, and their efficiency" [@rossi2004aevaluation, p. 3].

> "Program evaluation is the use of social research methods to systematically investigate the effectiveness of social intervention programs in ways that are adapted to their political and organizational environments and are designed to inform social action to improve social conditions" [@rossi2004aevaluation, p. 16].

> "One aspect of evaluating a program ... is to assess how good the **program theory** is --- in particular, how well it is formulated and whether it presents a _plausible and feasible_ plan for improving the target social conditions" [@rossi2004bexpressing, p. 133, _emph. added_].

> "A **program's theory** is the conception of what must be done to bring about the intended social benefits. _As such it is the foundation on which every program rests_" [@rossi2004bexpressing, p. 133, _emph. added_].

> "For **program theory** to be assessed, ... it must first be _expressed clearly and completely_ enough to stand for review" [@rossi2004bexpressing, p. 133, _emph. added_].

> "... _evaluators often distinguish between **process (or implementation) evaluation** and **outcome (or impact) evaluation**_" [@rossi2004cassessing, p. 171, _emph. added_].

> "Program evaluation in Scheirer's (1994) words, 'verifies what the program is and whether or not it is delivered as intended to the targeted recipients'. It does not, however, attempt to assess the effects of the program on those recipients" [@rossi2004cassessing, p. 171].

> > "Where **process evaluation** is an ongoing function involving repeated measurements over time, it is referred to as **program monitoring**" [@rossi2004cassessing , p. 171, _emph. added_].

> > > "**Program process monitoring** [_emph. in orig_] is the continual measurement of intended outcomes of the program, usually of the social conditions it is intended to improve" [@rossi2004cassessing, p. 171].

> "The **changed conditions** are the **intended outcomes** or products of the programs. _Assessing the degree to which a program produces these outcomes is a core function of evaluators_" [@rossi2004dmeasuring, p. 203, _emph. added_].

> "A program's **intended outcomes** are ordinarily identified in the program's impact theory. _Sensitive and valid measurement of those outcomes_ is technically challenging but essential to assessing a program's success" [@rossi2004dmeasuring, p. 203, _emph. added_].

> > "... ongoing monitoring of outcomes can be critical to effective program management" [@rossi2004dmeasuring, p. 203].

> > "Interpreting the results of outcome measurement and monitoring ... presents a challenge to stakeholders because a given set of outcomes can be produced by factors other than program processes" [@rossi2004dmeasuring, p. 203].

\SFrule

# Mixed-Methods Research


> [One approach to mixed-methods research developed by @morgan1998practical and referred to here as the "**complimentary sequence**" approach, involves\] "... _combining_ qualitative and quantitative methods ..." [@morgan1998practical, p. 362, _emph. added_].

> "The core of [the **complimentary sequence**] approach is an effort to _integrate_ the complimentary strengths of different methods through a division of labor" [@morgan1998practical, p. 366, _emph. added_].

> > "This amounts to _using a qualitative and a quantitative method for different but well-coordinated purposes_ within the same overall research project" [@morgan1998practical, p. 366, _emph. added_].

> > "The division of labor is accomplished through _two basic decisions_ ..." [@morgan1998practical, p. 366, _emph. added_].

> > > [1\] "... a _priority_ decision that pairs a principal method with a complimentary method and ..." [@morgan1998practical, p. 366, _emph. added_].

> > > [2\] "... a _sequence_ decision that determines whether the complementary method precedes or follows the principal method" [@morgan1998practical, p. 366, _emph. added_].

> [_**Equal-status mixed-methods research designs**_ are those\] "... where _high quality_ qualitative and quantitative data are collected ... " [and] "... the qualitative and quantitative research paradigms are given equal weight" [@stefurak2016mixed, p. 347].

> > "Sometimes it is said that paradigms are incommensurable and cannot be mixed. _However, they can be, using a **dialectical and dialogic logic**. That is why **equal-status mixed methods designs** are also called **interactive mixed methods designs**_" [@stefurak2016mixed, p. 347, _emph. added_]


`r tufte::newthought("\\Large{Mixed-methods research, in general, is:}")`

\vspace*{1em}

\LARGE{``}

> > ... a research approach or methodology:

> > - focusing on research questions that call for real-life contextual understandings, multi-level perspectives, and cultural influences;

> > - employing rigourous quantitative research assessing magnitude and frequency of constructs and rigorous qualitative research exploring the meaning and understanding of constructs;

> > - utilizing multiple methods (e.g., intervention trials and in-depth interviews);

> > - _intentionally integrating or combining these methods to draw on the strengths of each_;

> > - framing the investigation within philosophical and theoretical positions

\vspace*{-1em}

> > `r tufte::quote_footer("\\LARGE{''}")`

> > `r tufte::quote_footer("@creswell2016best, (p. 4, _emph. added_)")`

\SFrule

# Qualitative Research Methods


> "Qualitative approaches to research reflect an underlying philosophy of science and set of methods that embody many of the values of community research and action (Banyard & Miller, 1998)" [@stein2004asking, p. 21].

> "Some community scholars advocate qualitative approaches as a way to better understand individual diversity and the nuance of social context" [@stein2004asking, p. 21].

> "By emphasizing detailed, first-hand descriptions of people and settings, qualitative approaches methods are thought to enhance the study of behavior embedded in a larger social world (Trickett, 1996)" [@stein2004asking, p. 21].

> "Qualitative methods are also used to arrive at more ecologically-sensitive constructs upon which quantitative measures can be based" [@stein2004asking, p. 21].

> "Qualitative findings are said to help dispel misconceptions about marginalized populations perpetuated by the use of quantitative measures originally developed with mainstream samples (Dumka [et al.], 1998; Maton [et al.], 1998)" [@stein2004asking, p. 21].

> [Qualitative research is comprised of a set of tools designed, in large part, to\] "... facilitate researchers' knowledge about the experiences and perspectives of the group under study, as well as the development of research instruments that are useful and relevant" [@hughes2002using, p. 776].

> "**Focus groups** are in-depth group interviews employing relatively homogenous groups to provide information around topics specified by researchers" [@hughes2002using, p. 776, _emph. added_].

> [Focus groups\] "... have several strengths that make them particularly useful for facilitating research that reflects the social realities of a cultural group" [@hughes2002using, p. 776].

> "Focus groups provide researchers with _direct access_ to the language and concepts participants use to _structure their experiences_ and to think and talk about a designated topic" [@hughes2002using, p. 776, _emph. added_].

> "Within-group homogeneity prompts focus group participants to elaborate stories and themes that help researchers understand how participants structure and organize their social world" [@hughes2002using, p. 776].

> "In their reliance on social interaction, focus groups can also help researchers identify cultural knowledge that is shared among group members as well as to appreciate the range of different experiences individuals within a group may have" [@hughes2002using, p. 776].

> [Qualitative methods bring\] "... researchers closer to a _phenomenological understanding_ of a cultural group. Such an understanding can help investigators ask better research questions and develop the measures needed to study them" [@hughes2002using, p. 776, _emph. added_].

\SFrule

# Quantitative Research Methods


> [Quantitative methods\] "... facilitate rigorous hypotheses testing, produce research that is both internally valid and externally generalizable, and assess cause-and-effect relationships between constructs" [@connell2016introduction, p. 121].

> "... the quantitative methods used by community-based researchers provide a strong framework for investigating complex and contextualized phenomena in their own right" [@connell2016introduction, p. 121].

> "To maintain pace with the field's complex theories of the 'interplay between people and contexts' [@shinn2000cross, p. 185], community researchers should use data-analytic methods that best represent the relationship of ecological and contextual domains to the phenomena being investigated. This means that community researchers need to adopt measurement approaches that do a better job of capturing contextual information, such as social network analysis (SNA) or geographic information systems (GIS) methods [@luke2005getting], or 'ecometric' approaches (Raudenbush & Sampson, 1999, p. 3)" [@connell2016introduction, pp. 121--122].

> > "Community researchers also must make greater use of data-analytic methods that incorporate contextual (i.e., setting-level) and cross-level (i.e., interactions between setting-level and individual-level) effects ..., as well as more complex processes (e.g., indirect or mediating effects, moderation effects) cross-sectionally, longitudinally, and across contextual settings ..." [@connell2016introduction, p. 122].

> > "... analytic methods should be dynamic and adaptable to the challenges of complex research designs and data structures" [@connell2016introduction, p. 122].

> > > "... previous examinations of the state of the field's statistical methods [e.g., @luke2005getting] revealed that community researchers continue to rely on more traditional data-analytic methods (e.g., analysis of variance [ANOVA], regression, and correlation), rather than methods permitting greater complexity (e.g., structural equation modeling [SEM], cluster analysis, and SNA) or contextualization (e.g., multilevel modeling [MLM] and GIS analysis)" [@connell2016introduction, p. 122].




\newpage

# \centerline{\textsc{\huge{(1.b.) Discuss an application of the method}}}






\newpage

# References

\refs
