---
title: "Applied Community Psychology Working Bibliography"
author: "Rachel M. Smith"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---

```{r echo=FALSE, results='hide'}
cites <- data.frame(Citations = c("\\textcite{aea2004guiding}", "\\textcite{ajzen2005influence}", "\\textcite{balcazar2004participatory}", "\\textcite{baumeister2010self}", "\\textcite{bickman1987functions}", "\\textcite{braverman2013negotiating}", "\\textcite{cannuscio2009visual}", "\\textcite{case2014ethnography}", "\\textcite{chavis1999sense}", "\\textcite{christie2010insight}", "\\textcite{cohen1985stress}", "\\textcite{corona2009richmond}", "\\textcite{crosby2006understanding}", "\\textcite{de2001qualitative}", "\\textcite{durlak1997primary}", "\\textcite{dutta2016ethnographic}", "\\textcite{falconer2011validity}", "\\textcite{fazio1986attitudes}", "\\textcite{fowler1995improving}", "\\textcite{garcia1999community}", "\\textcite{glenwick2016handbook}", "\\textcite{groves2009survey}", "\\textcite{gurin2002diversity}", "\\textcite{harachi1999opening}", "\\textcite{ialongo1999proximal}", "\\textcite{jason2004participatory}", "\\textcite{johnson2013exploring}", "\\textcite{kellogg2004logic}", "\\textcite{kelly1971qualities}", "\\textcite{kloos2009social}", "\\textcite{kloos2012community}", "\\textcite{kundin2010conceptual}", "\\textcite{leary2010affiliation}", "\\textcite{lewicka2011place}", "\\textcite{lewin1951field}", "\\textcite{lohman2016geographic}", "\\textcite{luke2000smoke}", "\\textcite{luke2005getting}", "\\textcite{lyseen2014review}", "\\textcite{markus1991culture}", "\\textcite{mcmillan1986sense}", "\\textcite{mendoza2013using}", "\\textcite{miller2005learning}", "\\textcite{moane2003bridging}", "\\textcite{mortensen2010full}", "\\textcite{nelson2001building}", "\\textcite{nelson2014community}", "\\textcite{nelson2014early}", "\\textcite{nicotera2007measuring}", "\\textcite{oishi2010social}", "\\textcite{orsini2012collaborative}", "\\textcite{parker2006constructing}", "\\textcite{pretty2003sense}", "\\textcite{proshansky1983place}", "\\textcite{quon2009gis}", "\\textcite{rappaport1987terms}", "\\textcite{reis1988intimacy}", "\\textcite{reis2010social}", "\\textcite{riger1993s}", "\\textcite{rodriguez2013cooking}", "\\textcite{rossi2003evaluation}", "\\textcite{ryan2014focus}", "\\textcite{schwarz2001asking}", "\\textcite{seidman1988back}", "\\textcite{shadish1991foundations}", "\\textcite{shadish1998evaluation}", "\\textcite{sherif1998experiments}", "\\textcite{shinn1991social}", "\\textcite{shinn2003community}", "\\textcite{shinn2014capabilities}", "\\textcite{smith2015rebuilding}", "\\textcite{speer1995community}", "\\textcite{spreitzer1995empirical}", "\\textcite{stein2004asking}", "\\textcite{stokols1992establishing}", "\\textcite{sullivan2006assessing}", "\\textcite{sullivan2011retail}", "\\textcite{tajfel2004social}", "\\textcite{taylor1998social}", "\\textcite{taylor2000biobehavioral}", "\\textcite{thornton2011using}", "\\textcite{townley2009understanding}", "\\textcite{townley2011reconcilable}", "\\textcite{trickett2011water}", "\\textcite{wang1997photovoice}", "\\textcite{watts1992elements}", "\\textcite{weitzman2013good}", "\\textcite{wise2015placing}", "\\textcite{wright2007housing}", "\\textcite{ziersch2005neighbourhood}"))

knitr::kable(cites, row.names = FALSE)
```

\onehalfspacing

1. \fullcite{aea2004guiding}
1. \fullcite{ajzen2005influence}
1. \fullcite{balcazar2004participatory}
1. \fullcite{baumeister2010self}
1. \fullcite{bickman1987functions}
1. \fullcite{braverman2013negotiating}
1. \fullcite{cannuscio2009visual}
1. \fullcite{case2014ethnography}
1. \fullcite{chavis1999sense}
1. \fullcite{christie2010insight}
1. \fullcite{cohen1985stress}
1. \fullcite{corona2009richmond}
1. \fullcite{crosby2006understanding}
1. \fullcite{de2001qualitative}
1. \fullcite{durlak1997primary}
1. \fullcite{dutta2016ethnographic}
1. \fullcite{falconer2011validity}
1. \fullcite{fazio1986attitudes}
1. \fullcite{fowler1995improving}
1. \fullcite{garcia1999community}
1. \fullcite{glenwick2016handbook}
1. \fullcite{groves2009survey}
1. \fullcite{gurin2002diversity}
1. \fullcite{harachi1999opening}
1. \fullcite{ialongo1999proximal}
1. \fullcite{jason2004participatory}
1. \fullcite{johnson2013exploring}
1. \fullcite{kellogg2004logic}
1. \fullcite{kelly1971qualities}
1. \fullcite{kloos2009social}
1. \fullcite{kloos2012community}
1. \fullcite{kundin2010conceptual}
1. \fullcite{leary2010affiliation}
1. \fullcite{lewicka2011place}
1. \fullcite{lewin1951field}
1. \fullcite{lohman2016geographic}
1. \fullcite{luke2000smoke}
1. \fullcite{luke2005getting}
1. \fullcite{lyseen2014review}
1. \fullcite{markus1991culture}
1. \fullcite{mcmillan1986sense}
1. \fullcite{mendoza2013using}
1. \fullcite{miller2005learning}
1. \fullcite{moane2003bridging}
1. \fullcite{mortensen2010full}
1. \fullcite{nelson2001building}
1. \fullcite{nelson2014community}
1. \fullcite{nelson2014early}
1. \fullcite{nicotera2007measuring}
1. \fullcite{oishi2010social}
1. \fullcite{orsini2012collaborative}
1. \fullcite{parker2006constructing}
1. \fullcite{pretty2003sense}
1. \fullcite{proshansky1983place}
1. \fullcite{quon2009gis}
1. \fullcite{rappaport1987terms}
1. \fullcite{reis1988intimacy}
1. \fullcite{reis2010social}
1. \fullcite{riger1993s}
1. \fullcite{rodriguez2013cooking}
1. \fullcite{rossi2003evaluation}
1. \fullcite{ryan2014focus}
1. \fullcite{schwarz2001asking}
1. \fullcite{seidman1988back}
1. \fullcite{shadish1991foundations}
1. \fullcite{shadish1998evaluation}
1. \fullcite{sherif1998experiments}
1. \fullcite{shinn1991social}
1. \fullcite{shinn2003community}
1. \fullcite{shinn2014capabilities}
1. \fullcite{smith2015rebuilding}
1. \fullcite{speer1995community}
1. \fullcite{spreitzer1995empirical}
1. \fullcite{stein2004asking}
1. \fullcite{stokols1992establishing}
1. \fullcite{sullivan2006assessing}
1. \fullcite{sullivan2011retail}
1. \fullcite{tajfel2004social}
1. \fullcite{taylor1998social}
1. \fullcite{taylor2000biobehavioral}
1. \fullcite{thornton2011using}
1. \fullcite{townley2009understanding}
1. \fullcite{townley2011reconcilable}
1. \fullcite{trickett2011water}
1. \fullcite{wang1997photovoice}
1. \fullcite{watts1992elements}
1. \fullcite{weitzman2013good}
1. \fullcite{wise2015placing}
1. \fullcite{wright2007housing}
1. \fullcite{ziersch2005neighbourhood}
