# Social \& Community Interventions \todo

\newpage
# Advanced Applied Social & Community Psychology Syllabus

## Social Psychology

- [x] Kelly, J.G. (1971)
- [x] Kloos, Hill, Thomas, Wandersman, Elias, & Dalton (2012)
- [x] Lewin, K. (1951)
- [x] Taylor, S.E. (1998)
- [x] Mortensen, C. & Cialdini, R. (2010)
- [x] Reis, H. T., & Gosling, S. D. (2010)
- [x] Balcazar, F.E., Taylor, R.R., Keilhorner, G.W., Tamley, K., Benziger, T., Carlin, N., & Johnson, S. (2004)
- [x] Luke, D.A. (2005)
- [x] Stein, C.H., & Mankowski, E.S. (2004)
- [x] Baumeister, R. (2010)
- [x] Markus, H. R., & Kitayama, S. (1991)
- [x] Fazio, R. H. (1986)
- [x] Fishbein, M., & Ajzen, I. (2005)
- [x] Cohen, S., & Wills, T. A. (1985)
- [x] Leary, M. R. (2010)
- [x] Reis, H. T., ^ Shaver, P. (1988)
- [x] Taylor, S. E., Klein, L. C., Lewis, B. P., Gruenewald, T. L., Gurung, R. A., & Updegraff, J. A. (2000)
- [x] Crosby, F. J., Iyer, A., & Sincharoen, S. (2006)
- [x] Gurin, P., Dey, E.L., Hurtado, S., & Gurin, G. (2002)
- [x] Sherif, M. (1998)
- [x] Tajfel, H. & Turner, J. C. (1986)
- [x] Chavis, D. M., & Pretty, G. M. (1999)
- [x] Rappaport, J. (1987)
- [x] Riger, S. (1993)
- [x] Shinn, M., & Toohey, S.M. (2003)
- [x] Spreitzer, G. M. (1995)

## Community Psychology

- [x] Chavis, D. M., & Pretty, G. M. (1999)
- [x] Garcia, I., Giuliani, F., & Wiesenfeld, E. (1999)
- [x] Durlak, J. A., & Wells, A. M. (1997)
- [x] Miller, R.L., & Shinn, M. (2005)
- [x] Nelson, G., Stefancic, A., Rae, J., Townley, G., Tsemberis, S., Macnaughton, E., ... & Goering, P. (2014)
- [x] Seidman, E. (1988)
- [x] Speer, P. W., & Hughey, J. (1995)
- [x] Shinn, B. (in press)
- [x] Shinn, M., Knickman, J. R., & Weitzman, B. C. (1991)
- [x] Moane, G. (2003)
- [x] Nelson, G., Prilleltensky, I., & MacGillivary, H. (2001)
- [x] Townley, G., Kloos, B., Green, E.P., & Franco, M. (2011)
- [x] Trickett, E.J. (2011)
- [x] Watts, R.J. (1992)

\newpage
# Program Evaluation

- [x] Rossi, P. H., Lipsey, M. W., & Freeman, H. E. (2003)
- [x] Bickman, L. (1987)
- [x] Shadish, W. (1998)
- [x] Corona, R., Gonzalez, T., Cohen, R., Edwards, C., & Edmonds, T. (2009)
- [x] American Evaluation Association. (2004)
- [x] Schwarz, N. & Oyserman, D. (2001)
- [x] Braverman, M. (2013)
- [x] Weitzman, B. & Silver, D. (2013)
- [x] Harachi, T.W., Abbott, R.D., Catalano, R.F., Haggerty, KP & Fleming, C.B. (1999)
- [x] Ialongo, N.S., Werthamer, L., Kellam, S.G., Brown, C.H., Wang, S., & Lin, Y. (1999)
- [x] Ryan,K., Gandha, T., Culbertson, M., & Carlson, C. (2014)
- [x] de Anda, D. (2001)
- [x] Rodriguez, J., Applebaum, J., Stephenson-Hunter, C., Tinio, A. & Shapiro, A. (2013)
- [x] Orsini, M., Wyrick, D., & Milroy, J. (2012)
- [x] Christie, C., & Fleischer, D., ( 2010)
- [x] Falconer, M., Clark, M., & Parris, D. (2011)
- [x] Johnson, J., Hall, J. Greene, J. & Ahn, J. (2013)
- [x] Delia M. Kundin (2010)

\newpage
# Place-Based Research

- [x] Oishi, S., & Graham, J. (2010)
- [x] Proshansky, H. M., Fabian, A. K., & Kaminoff, R. (1983)
- [x] Lewicka, M. (2011)
- [x] McMillan, D. W., & Chavis, D. M. (1986)
- [x] Pretty, G. H., Chipuer, H. M., & Bramston, P. (2003)
- [x] Stokols, D. (1992)
- [x] Kloos, B., & Shah, S. (2009)
- [x] Wright, P. A., & Kloos, B. (2007)
- [x] Shinn, M., & Toohey, S.M. (2003)
- [x] Nicotera, N. (2007)
- [x] Ziersch, A. M., Baum, F. E., MacDougall, C., & Putland, C. (2005)
- [x] Sullivan, D. M. (2006)
- [x] Sullivan, D. M., & Shaw, S. C. (2011)
- [x] Wang, C., & Burris, M. A. (1997)
- [x] Smith, B. T., Padgett, D. K., Choy-Brown, M., & Henwood, B. F. (2015)
- [x] Cannuscio, C. C., Weiss, E. E., Fruchtman, H., Schroeder, J., Weiner, J., & Asch, D. A. (2009)
- [x] Case, A. D., Todd, N. R., & Kral, M. J. (2014)
- [x] Dutta, U. (2016)
- [x] Lohmann, A. (2016)
- [x] Quon Huber, M. S., Van Egeren, L. A., Pierce, S. J., & Foster-Fishman, P. G. (2009)
- [x] Lyseen, A. K., Nøhr, C., Sørensen, E. M., Gudes, O., Geraghty, E. M., Shaw, N. T., & Bivona-Tellez, C. (2014)
- [x] Thornton, L. E., Pearce, J. R., & Kavanagh, A. M. (2011)
- [x] Luke, D., Esmundo, E., & Bloom, Y. (2000)
- [x] Mendoza, N. S., Conrow, L., Baldwin, A., & Booth, J. (2013)
- [x] Townley, G., Kloos, B., & Wright, P. A. (2009)
- [x] Wise, N.(2015)
- [x] Parker, B. (2006)

\newpage
# Focus Groups \todo

\newpage
# Qualitative Data Analysis \todo

\newpage
# Mixed Methods Research \todo

\newpage
# Survey Research Methods \todo

\newpage
# Psychological Measurement \todo

\newpage
# Catagorical Data Analysis

\newpage
# Hierarchical Linear Modeling

\newpage
# 
