// <script>
// TODO: MAKE THIS SHIT INTO A LOOP !! //
// var dsfx_st = [1, 21, 31];
// var dsfx_nd = [2, 22]
// var dsfx_rd = [3, ]
// dsfx_st[1] = 1
// for(var i = 0; i < dsfx.length; i++){
  // if (dsfx == )
// };

var month = new Array(11);
month[0] = "January";
month[1] = "February";
month[2] = "March";
month[3] = "April";
month[4] = "May";
month[5] = "June";
month[6] = "July";
month[7] = "August";
month[8] = "September";
month[9] = "October";
month[10] = "November";
month[11] = "December";
var dsfx = new Array(31);
dsfx[1] = "st"
dsfx[2] = "nd"
dsfx[3] = "rd"
dsfx[4] = "th"
dsfx[5] = "th"
dsfx[6] = "th"
dsfx[7] = "th"
dsfx[8] = "th"
dsfx[9] = "th"
dsfx[10] = "th"
dsfx[11] = "st"
dsfx[12] = "nd"
dsfx[13] = "rd"
dsfx[14] = "th"
dsfx[15] = "th"
dsfx[16] = "th"
dsfx[17] = "th"
dsfx[18] = "th"
dsfx[19] = "th"
dsfx[20] = "th"
dsfx[21] = "st"
dsfx[22] = "nd"
dsfx[23] = "rd"
dsfx[24] = "th"
dsfx[25] = "th"
dsfx[26] = "th"
dsfx[27] = "th"
dsfx[28] = "th"
dsfx[29] = "th"
dsfx[30] = "th"
dsfx[31] = "st"
var d = new Date(document.lastModified);
var theMonth = month[d.getMonth()];
var theDate = d.getDate();
var theDateS = dsfx[d.getDate()];
var theYear = d.getFullYear();
var x = "Last Updated: ";
var y = theDate + theDateS.sup() + " " + theMonth + ", " + theYear;
document.getElementById("lmText").innerHTML = x;
document.getElementById("lmDate").innerHTML = y;
// </script>
// var mon = new Array(11);
// mon[0] = "Jan";
// mon[1] = "Feb";
// mon[2] = "Mar";
// mon[3] = "Apr";
// mon[4] = "May";
// mon[5] = "Jun";
// mon[6] = "Jul";
// mon[7] = "Aug";
// mon[8] = "Sep";
// mon[9] = "Oct";
// mon[10] = "Nov";
// mon[11] = "Dec";
