# Personal Statement

My research is strongly informed by my community-based work. Prior to beginning the graduate program here Oregon, I served as an shelter, crisis line, and legal advocate at an Atlanta-based intimate partner violence (IPV) response and prevention organization^[[Partnership Against Domestic Violence](padv.org) and the Safe Families Office at the Superior Court of Fulton County]. Serving as an advocate in multiple settings (i.e., crisis line, shelter, and legal services) allowed me to integrate my academic-based understanding of survivors' and perpetrators' experiences with the contextual framework of the structure and organization of local IPSV coordinated community response and prevention efforts.

As a graduate student researcher, I have continued to be an active member of the violence intervention and prevention community in Oregon by working closely with a diverse network of community partners throughout the state to address the range of community health and social justice issues  intersecting with violence and oppression intervention and prevention efforts. In order to engrain myself as a researcher within local and statewide coordinated community response efforts in I relocated to Portland three months before my graduate studies would officially begin. During those initial three months, I began a 12-month internship with the [Oregon Attorney General's Sexual Assault Task Force's (ORSATF)](http://oregonsatf.org) Prevention and Education Subcommittee (PEC), became a founding member of a local community organizing group focused on engaging men as allies in efforts to prevent violence against women ([Men Engaging Now](https://www.facebook.com/MENPDX/)), and volunteered for and completed multiple trainings with the [YWCA of Greater Portland's Social Justice Program](http://www.ywcapdx.org/what-we-do/social-justice/).

I have since served as an appointed advisory committee member with the ORSATF Prevention and Education Subcommittee and the prevention liaison for the ORSATF Offender Management Subcommittee. My work with the ORSATF included reviewing and updating the statewide sexual violence prevention plan and reviewing rape prevention and education grantee programs' progress and needs assessment data. I co-represented the state of Oregon and Portland State University as part of the ORSATF’s Campus Sexual Violence Prevention Workgroup's participation in a two-day sexual violence prevention action planning meeting hosted by the American Public Health Association and Centers for Disease Control and Prevention's Division of Violence Prevention in Atlanta, GA. This action planning meeting was conducted as part of the White House Task Force to Protect Students from Sexual Assault's "Not Alone" project.

I also continued to participate in the Tri-County Batterer Intervention Providers Network monthly meetings, and continued my membership with the Men Engaging Now Coordinating Committee, with whom I have co-presented multiple lectures and workshops related to social justice activism and violence prevention. I also worked with the Oregon Center for Children and Youth with Special Healthcare Needs where I assisted with the data entry and analysis for the organization's state-wide needs assessment with Oregon families and healthcare providers.

Collectively, these community-based activities facilitated my participation in Oregon's coordinated community response to ending violence against women and marginalized populations, and has led to several practical and intellectual resources vital to the success of my program of research. In particular, my community engagement provides access to the populations of interest for my research (i.e., LGBTQ women and women with histories of IPV perpetration and victimization), and insights on the design and implementation of my research activities.

The knowledge and perspectives I have gained through my work in my local communities, both in Oregon as a graduate student researcher and previously in Atlanta, GA while completing my undergraduate degree, motivated the design and implementation of my National Science Foundation (NSF) Graduate Research Fellowship program of research. My Masters Thesis project constituted the first phase of my NSF-proposed program of research, in which I conducted a series of one-on-one interviews and one focus group with LGBTQ women recruited from the Greater Portland, OR area. The success of this project hinged on my ability to maintain working collaborative relationships with a variety of community-based professionals, who assisted with direct and indirect participant recruitment and who I am currently working with to disseminate the study's qualitative findings and corresponding recommendations for IPV-related government and community-based service providers in Oregon.

Throughout the course of designing and implementing my Masters Thesis project, I also served as a graduate research assistant on a national survey of IPV intervention programs' standards committees. The data collection management for this study involved my coordination of fellow graduate and undergraduate research assistants to recruit one or more representatives from each U.S. state's IPV intervention programs' standards committee to participate in an audio-recorded telephone interview with a member from our research team. My responsibilities also included overseeing and participating in transcribing the telephone interview recordings, developing and implementing a data analysis plan for both the quantitative and qualitative interview data, and developing presentations and reports to be disseminated to relevant local and national stakeholders (e.g., Oregon's and other states' IPV intervention programs' standards committees, IPV intervention program providers, etc.).

In addition to the project and organizational management skills gained from my roles in the latter national survey project and my Masters Thesis project, I used the unique circumstance of having two simultaneous leadership roles during my first two years of graduate school as an opportunity to further develop and apply several of the data analytic and presentation techniques I learned through my graduate coursework. I became proficient in developing and implementing team-based protocols for qualitative data analytic procedures including Grounded Theory methods [@charmaz2006constructing; @corbin1990basics], _thematic analysis_, and _content analysis_; as well as quantitive data analytic techniques for both categorical and continuous data (e.g., _cluster analysis_, _inter-rater reliability_, _factor analysis_, _multple linear regression_, _mixed-effects,_ and _structural equation modeling_, etc.). These data analytic skills have further allowed me to become proficient in multiple statistical programming software packages and languages including _R_, _SQL_, _Mplus_, _SAS_, and _SPSS_.

## Readiness for Comprehensive Examination

Collectively, my completed graduate coursework (see _Section A._) and the above outlined community-engaged research activities and experiences have prepared me to demonstrate my aptitude as a community psychology researcher and scholar. I therefore propose demonstrating my expertise in this field via the proposed _Major Area Paper_ (see _Section C._`), an oral examination on the paper's content and community psychological theory and research, and a written and oral examination in the _Community Methods_ minor area. Regarding the latter, because a large portion of my graduate coursework (see _Section A._) has focused on mixed-methods research, I believe my minor area examination would be most reflective of my graduate training in community psychology methods if it were specifically focused around _mixed-methods community psychology research_.

# References
