# (C) Major Area Paper Outline <!--`(2-3 pages)`-->

## I. Background \& Significance

I propose conducting a systematic critical review of research conducted with marginalized populations, with a specific focus on violence-related research with sexual minority women (SMW).^[[see relevance to dissertation topic]] The critical review will attempt to map core components of community psychological theory and methodologies to the body of research available under the above-defined content and research discipline scopes. In particular, I am interested in evaluating the extent to which community psychological theory and methodologies are implemented, or not, in community psychology-based research related to the phenomenon of interest (i.e., intimate partner violence). I am further interested in examining how the implementation of community psychological research has evolved over time since the origination of the field, as well as potential trajectories based on the current state of discourse within Community Psychology and closely related research and practice disciplines.

Community psychological theory values the notion that the communities in which research is taking place and/or affecting (whether directly or indirectly) should be as involved as possible in all phases of the research process, rather than solely as anonymous data points in the analysis. Community psychology thus favors inclusion over exclusion, participant voices equally with researchers' voices, and participatory and/or purposive sampling methods over convenience sampling methods. The reviewed literature will be evaluated and critiqued according to these types of community psychological standards regarding (1) _research methodologies_, (2) _data analytic approaches_, (3) _interpretations of findings_, and (4) _research dissemination._


## II. Theoretical Grounding

In a sense, the proposed review's theoretical grounding is best summarized in terms of the of the Community Psychology Practice Council's [_"Theory into Action Bulletin"_](http://www.scra27.org/what-we-do/practice/practice-council-initatives/theory-action-bulletin/)^[[Society for Community Research and Action (SCRA)](http://www.scra27.org/)]. The review will be grounded in theories related to action-oriented research and their applications [@chandler2003transforming; @brydon-miller2003why; @friedman-nimz2006blending; @kelly2004community; @noffke1997professional; @prilleltensky2001value-based; @prilleltensky1997values; @seidman2012emerging], as well as social and community psychological theories related to female same-sex intimate partner violence. In particular, I am interested in the intersections that exist across these theoretical, methodological, and problem-specific domains in terms of their actual applications and manifestations in various settings. Below is a list of theoretical and conceptual frameworks specifically guiding the proposed review.

`r tufte::newthought("Theory Specific to Community Psychology (CP):")`

- _The Action Research Cycle & Community-Based Participatory Action Research_ [CBPR; @fine2004participatory; @chandler2003transforming; @brydon-miller2003why; @friedman-nimz2006blending; @kelly2004community; @noffke1997professional; @prilleltensky2001value-based; @prilleltensky1997values; @seidman2012emerging; @anders1966action]
- _Ecological systems theory and the Social Ecological Model_ [@stokols1996translating; @visser2007social; @walker2006handful; @centers2015social; @kloos2009social; @anderies2004framework; @baral2013modified; @stokols1996translating]
- _Community Empowerment & Individual Empowerment_ [@speer1995community; @riger1993what; @beeker1998community; @cobb1993empowerment; @collins2002black]
- _[Community] Health Promotion_ [@stokols1996translating]

`r tufte::newthought("Theory Related to both Community Psychology and IPV Intervention and Prevention:")`

- _Coordinated Community Response_ [CCR; @gondolf2007theoretical; @barner2011interventions; @dutton2007duluth]
- _Minority Stress Theory & Resilience_ [MS; @meyer2003prejudice; @meyer2010right; @meyer1995minority; @meyer2015resilience]
- _Risk Factors vs. Protective Factors_ [@baral2013modified; @whitaker2014linking; @tharp2013systematic; @walton-moss2005risk; @heckert2004battered]

`r tufte::newthought("Intersecting Community Psychology Theory \\& Research Methodology")`

- _Grounded Theory Methods_ [@charmaz2006constructing; @corbin1990basics; @strauss1994grounded]
- _Mixed-Methods Research_ [@morgan2014mmr; @creswell2013research; @greene1989toward; @johnson2007toward]
- _Program Evaluation_ [@greene1989toward; @kidder1987qualitative; @mertens2012program; @owen1999program; @royse2009program]

## III. Paper Parameters / Systematic Literature Review Methodology

`r tufte::newthought("A. Key literature search strategy")`

The scope of reviewed research will include published work in the Community Psychology discipline, as well as research published in related fields such as Social and Clinical Psychology, Social Work, Public Health, and Sociology.

`r tufte::newthought("B. Focal data bases.")` The collection process will primarily utilize the robust literature search capabilities provided by _PsychInfo_, _Google Scholar_, and _Web of Science/Web of Knowledge_. In addition, resources specific to community psychology, including _The American Journal of Community Psychology_, [_"Theory into Action Bulletin"_](http://www.scra27.org/what-we-do/practice/practice-council-initatives/theory-action-bulletin/), and [_"The Community Toolbox" (TCB)_](http://ctb.ku.edu/en), will be surveyed as potential sources of information for this review. In the case that these databases and resources do not collectively yield a substantial sample of literature appropriate under the parameters of this review, additional databases from related research fields will be used in finding additional research for inclusion in the review. Potential additional databases include the _Gender Studies Database_ (Social Psychology and Sociology), _PubMed_ (Public Health and Clinical Psychology), and _Social Services Abstracts_ (Social Work).

`r tufte::newthought("C. Key search terms.")` Key search terms will focus on both the focal research content area for this paper (i.e., female same-sex intimate partner vioelence) and terms related to community-psychological methods or theories. Sample _Boolean_ search queries are provied below to demonstrate this aspect of the proposed search methodology.

- `("intimate partner violence" OR "domestic violence") OR (Aggression OR violence) `
- `("intimate partner violence" OR "domestic violence") AND (intervention OR evaluation)`
- `("intimate partner violence" OR "domestic violence") AND (prevention)`
- `("intimate partner violence" OR "domestic violence") OR (Aggression OR violence) AND (lesbian OR bisexual OR "sexual minority") AND women`
- `female AND ("same-sex" OR "same-gender") AND ("intimate partner violence" OR "domestic violence") AND (intervention OR evaluation)`
- `female AND ("same-sex" OR "same-gender") AND ("intimate partner violence" OR "domestic violence") AND (ecological OR multilevel)`

`r tufte::newthought("D. Inclusion/exclusion criteria.")`

- **Dates published**: Between 1965 & 2016
- **Topics**:
    - Intimate partner violence (IPV) among sexual minority women (causes, correlates, and/or consequences)
    - IPV intervention and/or prevention strategies/approaches
    - IPV intervention and/or prevention program evaluation
- **Research & Practice Fields/Frameworks**:
    - Community Psychology
    - Other Psychology Sub-fields (Social, Clinical, Organizational)
    - Sociology
    - Public Health
    - Social Work


## IV. Integrative Literature Review & Critique of Literature

Research conducted within the subset of community psychology focused around intimate partner violence will be initially evaluated according to the level of inclusion and exclusion of the historically marginalized population of interest (i.e., sexual minority women). The implementation of community psychology methodologies and analytic approaches will then be reviewed within each of these categories (i.e., inclusion or exclusion of sexual minority women) in terms of (1) the appropriateness of the methods to the research question, (2) how the methods facilitated the inclusion or exclusion of sexual minority women, and (3) whether and how (where applicable) exclusion of sexual minority women is justified. 

## V. Summary of Findings & Applied Implications

`r tufte::newthought("1. Methodological Considerations.")` Are efforts made to ensure that _all available_ stakeholders' and informants' voices and accessibility considered equally, and that certain voices are not unjustifiably privileged over others?

`r tufte::newthought("3. Interpretations of Findings.")` Is feedback from key stakeholders and informants to the research accepted and genuinely considered by the core research team? Are efforts made to ensure that _all available_ stakeholders' and informants' voices and accessibility considered equally, and that certain voices are not unjustifiably privileged over others?

`r tufte::newthought("4. Research Dissemination.")` Are key stakeholders and informants to the research given access to reports of a given project's progress and/or findings? Is such access in fact accessible (i.e., free and easy to locate)?




# IX. Reading List

@anderies2004framework
- @anders1966action
- @baral2013modified
- @barner2011interventions
- @beeker1998community
- @brydon-miller2003why
- @centers2015social
- @chandler2003transforming
- @charmaz2006constructing
- @cobb1993empowerment
- @collins2002black
- @corbin1990basics
- @creswell2013research
- @dutton2007duluth
- @fine2004participatory
- @friedman-nimz2006blending
- @gondolf2007theoretical
- @greene1989toward
- @heckert2004battered
- @johnson2007toward
- @kelly2004community
- @kidder1987qualitative
- @kloos2009social
- @mertens2012program
- @meyer1995minority
- @meyer2003prejudice
- @meyer2010right
- @meyer2015resilience
- @morgan2014mmr
- @noffke1997professional
- @owen1999program
- @prilleltensky1997values
- @prilleltensky2001value-based
- @riger1993what
- @royse2009program
- @seidman2012emerging
- @speer1995community
- @stokols1996translating
- @strauss1994grounded
- @tharp2013systematic
- @visser2007social
- @walker2006handful
- @walton-moss2005risk
- @whitaker2014linking


# References
