# (E) Reading List

1. @anderies2004framework
2. @anders1966action
3. @baral2013modified
4. @barner2011interventions
5. @beeker1998community
6. @brydon-miller2003why
7. @centers2015social
8. @chandler2003transforming
9. @charmaz2006constructing
10. @cobb1993empowerment
11. @collins2002black
12. @corbin1990basics
13. @creswell2013research
14. @dutton2007duluth
15. @fine2004participatory
16. @friedman-nimz2006blending
17. @gondolf2007theoretical
18. @greene1989toward
19. @heckert2004battered
20. @johnson2007toward
21. @kelly2004community
22. @kidder1987qualitative
23. @kloos2009social
24. @mertens2012program
25. @meyer1995minority
26. @meyer2003prejudice
27. @meyer2010right
28. @meyer2015resilience
29. @morgan2014mmr
30. @noffke1997professional
31. @owen1999program
32. @prilleltensky1997values
33. @prilleltensky2001value-based
34. @riger1993what
35. @royse2009program
36. @seidman2012emerging
37. @speer1995community
38. @stokols1996translating
39. @strauss1994grounded
40. @tharp2013systematic
41. @visser2007social
42. @walker2006handful
43. @walton-moss2005risk
44. @whitaker2014linking


# References
