# Appendix D Clinician Rating Form [@gondolf2009clinician]

Date:

Subject Name:

Group Leader (initials): Site:

INSTRUCTIONS: Please rate the man named above on each of the listed criteria. Rate him using the 0 to 5 scale below based on your impressions and observations. Return the form immediately to the evaluation contact person. 5 = extremely present; 4 = very present; 3 = somewhat present; 2 = a little present; 1 = very little present; 0 = no opinion, uncertain, not applicable.


`_____` attendance: arrives at group session on time; socializes or lingers afterward; contacts program in advance about absence; has legitimate excuse for absences.

`_____` nonviolence: has not recently physically abused partner, children, or others; no apparent threats, intimidation, or manipulation.

`_____` sobriety: attends meeting sober; not high or drunk; no apparent abuse of alcohol or drugs during week; complying to ordered or referred drug and alcohol treatment.

`_____` acceptance: admits that violence and abuse exists; not minimizing, blaming, or excusing the problem; realizes responsibility for abuse; identifies contribution to problems

`_____` using techniques: takes conscious steps to avoid violence; refers to time-outs, self-talk, conflict resolution skills, etc.; does homework assignments or recommendations.

`_____` help seeking: seeks information about alternatives; discusses options with others in the group; calls other participants for help; open to referrals and future support.

`_____` process conscious: lets others speak one at time; acknowledges others’ contributions; asks questions of others without interrogating; heeds direction of counselors.

`_____` actively engaged: attentive body language and nonverbal response; maintains eye contact; speaks with feeling; follows topic of discussion in comments.

`_____` self-disclosure: reveals struggles, feelings, fears, and self-doubts; not withholding or evading issues; not sarcastic or defensive.

`_____` sensitive language: respectful of partner and women in general; nonsexist language and no pejorative slang; checks others who use sexist language.


-----
