# Discussion

This review aimed to provide a systematic and methodologically-focused overview and ecological analysis of the available IPV-related research conducted within Community Psychology and related research disciplines, with a particular focus on such research that is specifically inclusive of and applicable to sexual minority women. The motivations for this review lie in the author's awareness of an enduring critical dearth of research concerning sexual minority women's IPV-related experiences [see historical and contextual reviews provided in @smith2016community], as well as the benefits of the values-transparent and ecologically-valid lens reflected in community-psychological theory, research methodologies, and data analytic approaches.

## Limitations of This Review

The present review is specifically focused on the methodological quality of research conducted within the aforementioned frameworks and the corresponding implications for IPV-related research and intervention practice specific to sexual minority women. The lack of available empirical literature evaluating IPV-related interventions specifically inclusive of sexual minority women at the time this review was conducted posed an inherent limitation to the overall content of the present review. In addition and as previously noted (see _"Systematic Literature Search & Review Methods"_), the present review is confined to IPV-related interventions research conducted (a) in the United States and (b) within Community-Psychological and closely related research frameworks, and therefore does not provide a synthesis nor methodological evaluation of full body of available IPV-related research. The latter limits of this review cause a second limitation, which is that this review does not provide a systematic comparative analysis of U.S.-based IPV-related research conducted within Community Psychological frameworks versus research conducted outside of (a) the United States nor (b) Community Psychological research frameworks.

## Implications

To date, several literature reviews have been published to synthesize the available empirical research regarding intimate partner violence perpetrator intervention programs and their efficacy [@day2009programs; @dutton2007duluth; @gondolf2007theoretical; @mankowski2002collateral; @mcginn2016survivor; @babcock2004does; @babcock2016domestic; @tolman1995intervention]. A small subset of these reviews [e.g., @dutton2005gender; @dutton2006transforming] focus primarily on the research methods employed across the IPV perpetrator interventions literature. However, no known methodologically-focused systematic review is currently available that evaluates the literature through the community psychological lens provided here. The critical analysis of the literature presented here provides a unique perspective regarding the potential methodological mechanisms by which sexual minority women and other minoritized populations have been almost entirely excluded from IPV interventions research conducted within community psychological and related research and practice disciplines.

Collectively, the present evaluation of the ecological complexity, or lack thereof, among the reviewed literature reiterates the need for more robust and contextually-valid methods and analytic approaches in community-based and action-oriented IPV-related research. Incorporating methods and analytic approaches that intersect across the levels of the ecological model allows for both complex and broad-based investigations of and insights regarding not only a given phenomenon of interest, but also the design and implementation of social and community interventions. In fact, the observed disconnect between the individual, relationship, and societal levels of ecological analysis within the literature included in this analysis is an especially concerning limitation of this set of community-based IPV-related literature. Intimate partner and sexual violence inherently involve the close relationships among individuals, including relationships between the perpetrators and victims or survivors of intimate partner and sexual violence, as well as the close connections each party has with others outside of the immediate perpetrator/victim relationship. The latter group is a critical component of the context surrounding an individual's participation in an IPV perpetrator intervention, particularly given that individuals engaged in such programs are often required by either or both the programs themselves or the criminal justice system to have either limited or no contact with the victim(s) during their participation in the intervention. Thus, critically overlooked intersections exist between (a) IPV perpetrator intervention program participants and their peers and mentors within the intervention programs, as well as (b) the structural and cultural practices, institutions, and customs of the societies within which each of the former individuals and close interpersonal relationships exists.

Future research investigations specifically targeting intersections across ecological levels of analysis would provide important and much needed insights regarding intervention recipients' and intervention practitioners' experiences within and outside of the intervention programs. Such insights would inform the development, implementation, adaptation, and sustainability of future and existing community-based IPV intervention and, in particular, prevention programs. Further, focusing on the ecological validity of the methods we employ to develop, evaluate, and sustain IPV intervention and prevention efforts not only facilitates the complex levels of analysis necessary for addressing social and public health problems as complex as intimate partner violence, but also facilitates inclusivity of marginalized populations (e.g., sexual minority women) within community scientific IPV-related research.

Finally, a key to addressing the present review's above-described limitations is the continued burgeoning of IPV-related research that is specifically inclusive of lesbian, gay, bisexual, transgender, and queer populations. It is crucial that this growing body of research actively works to avoid the limitations consistently found across research conducted under the goals of alleviating social and public health issues such as intimate partner and sexual violence. Specifically, the growing IPV-related literature, both within and outside of Community Psychology and related disciplines, would benefit from vigilant and critical reflexivity in terms of the intersections between the populations and contexts that are either over- or under-represented in our research and the research methods, tools, and analytic approaches we develop, learn, adapt, and employ.
